### ISSUE TITLE
[Bug] FTP directory listing breaks MC

### ISSUE THREAD

**Issue by povesma** [mucommander/mucommander#1003]
### Description

It war working fine with local files, and then after I tried FTP connection with credentials it behaved in non-expected way (did no change the directory, spontaneously showed a terminal window), I decided to restart the app.

When starting an app in MacOS Ventura 13.4.1 (M1 chip) I get:
`An error prevented muCommander from starting`

Details:
`java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
 at com.mucommander.ui.main.table.FileTableModel.getValueAt(FileTableModel.java:801)
 at com.mucommander.ui.main.table.FileTable.doAutoLayout(FileTable.java:1103)
 at com.mucommander.ui.main.table.FileTable.doLayout(FileTable.java:1151)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validateTree(Unknown Source)
 at java.desktop/java.awt.Container.validate(Unknown Source)
 at java.desktop/java.awt.Container.validateUnconditionally(Unknown Source)
 at java.desktop/java.awt.Window.show(Unknown Source)
 at java.desktop/java.awt.Component.show(Unknown Source)
 at java.desktop/java.awt.Component.setVisible(Unknown Source)
 at java.desktop/java.awt.Window.setVisible(Unknown Source)
 at com.mucommander.ui.main.WindowManager.lambda$createNewMainFrame$1(WindowManager.java:202)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
 at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:202)
 at com.mucommander.Application.run(Application.java:397)
 at com.mucommander.Application.run(Application.java:481)
 at com.mucommander.Activator.start(Activator.java:127)
 at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
 at org.apache.felix.framework.Felix.activateBundle(Felix.java:2429)
 at org.apache.felix.framework.Felix.startBundle(Felix.java:2335)
 at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
 at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
 at java.base/java.lang.Thread.run(Unknown Source)`

muCommander version 1.3.0, also happens on 1.4.0 nightly.
Removing/reinstalling the app does not help.

### Steps to reproduce

Create an FTP connection with authentication, save password, restart the app.

### Expected behavior

The application starts as usual.

### Actual behavior

When starting an app in MacOS Ventura 13.4.1 (M1 chip) I get:
`An error prevented muCommander from starting`

### muCommander version

1.3.0, 1.4.0 nightly (15 July 2023)

### Java version

"About" does not work.
java -version:

`openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)`

### Operating System type and version

MacOS Ventura 13.4.1 (M1 chip)

**Comment by pskowronek** [comment]
On intel mac can't reproduce. Tried both anonymous and with creds (used this server: https://stackoverflow.com/a/40135344/1715521). 

Can you provide screenshot, especially this part is intriguing "did no change the directory, spontaneously showed a terminal window".

**Comment by ahadas** [comment]
@povesma removing `~/Library/Preferences/muCommander/snapshot.xml` should make the application start.
and the Java version you wrote above is not the one that muCommander uses - we bundle the JRE with the application (Java 20)

**Comment by povesma** [comment]
Need to say that after ~14 hours of doing nothing (no reboot, deep hibernation only) it works like a charm (v. 1.4.0 nightly 15th of July 2023).
Anyway, it worth to check the logs :-)

**Comment by povesma** [comment]
@ahadas I did not remove `~/Library/Preferences/muCommander/snapshot.xml`, thank you for the advice. It would be nice to have this recommendation in the error message so users are not stuck with the not-working app.

Also, yes, once I have access to "About" it reads
`Java
Runtime version: 20
VM name: OpenJDK 64-Bit Server VM
VM version: 20+36
VM vendor: Eclipse Adoptium`

**Comment by povesma** [comment]
@pskowronek 

> Can you provide screenshot, especially this part is intriguing "did no change the directory, spontaneously showed a terminal window".

It happened with 1.3.0. Unfortunately, I did not make any screenshot :( and I couldn't reproduce the issue as the app did not start. Now (as I wrote above) it works as expected (1.4.0).

**Comment by ahadas** [comment]
> Anyway, it worth to check the logs :-)

yeah, you can find them in `~/Library/Preferences/muCommander/logs` - it would be great if you can share them so we can take a look, as otherwise it would be hard to reproduce this like @pskowronek wrote above

**Comment by povesma** [comment]
@ahadas @pskowronek 
[mucommander-2023-07-15.0.log](https://github.com/mucommander/mucommander/files/12067096/mucommander-2023-07-15.0.log)
