### ISSUE TITLE
An error prevented muCommander from starting

### ISSUE THREAD

**Issue by zlobjc** [mucommander/mucommander#107]
after update from 0.9.1 to 0.9.2 at first start. windows 10
```
java.lang.Error: Structure.getFieldOrder() on class com.mucommander.commons.file.util.Kernel32API$WIN32_FIND_DATA does not provide enough names ([cAlternateFileName, cFileName, dwFileAttributes, dwReserved0, dwReserved1, ftCreationTime, ftLastAccessTime, ftLastWriteTime, nFileSizeHigh, nFileSizeLow, nFileSizeLow]) to match declared fields ([cAlternateFileName, cFileName, dwFileAttributes])
 at com.sun.jna.Structure.getFields(Structure.java:913)
 at com.sun.jna.Structure.deriveLayout(Structure.java:1058)
 at com.sun.jna.Structure.calculateSize(Structure.java:982)
 at com.sun.jna.Structure.allocateMemory(Structure.java:363)
 at com.sun.jna.Structure.ensureAllocated(Structure.java:339)
 at com.sun.jna.Structure.ensureAllocated(Structure.java:329)
 at com.sun.jna.Structure.write(Structure.java:701)
 at com.sun.jna.Structure.autoWrite(Structure.java:1923)
 at com.sun.jna.Function.convertArgument(Function.java:505)
 at com.sun.jna.Function.invoke(Function.java:297)
 at com.sun.jna.Library$Handler.invoke(Library.java:212)
 at com.sun.proxy.$Proxy2.FindFirstFile(Unknown Source)
 at com.mucommander.commons.file.protocol.local.LocalFile.isSystem(LocalFile.java:639)
 at com.mucommander.commons.file.filter.AttributeFileFilter.accept(AttributeFileFilter.java:129)
 at com.mucommander.commons.file.filter.AbstractFileFilter.reject(AbstractFileFilter.java:76)
 at com.mucommander.commons.file.filter.AbstractFileFilter.match(AbstractFileFilter.java:70)
 at com.mucommander.commons.file.filter.AndFileFilter.accept(AndFileFilter.java:70)
 at com.mucommander.commons.file.filter.AbstractFileFilter.match(AbstractFileFilter.java:72)
 at com.mucommander.commons.file.filter.AbstractFileFilter.filter(AbstractFileFilter.java:85)
 at com.mucommander.commons.file.AbstractFile.ls(AbstractFile.java:537)
 at com.mucommander.ui.event.LocationManager.setCurrentFolder(LocationManager.java:79)
 at com.mucommander.core.LocationChanger$1.run(LocationChanger.java:106)
 at com.mucommander.core.LocationChanger.tryChangeCurrentFolderInternal(LocationChanger.java:120)
 at com.mucommander.ui.main.FolderPanel.tryChangeCurrentFolderInternal(FolderPanel.java:348)
 at com.mucommander.ui.main.tabs.FileTableTabs.show(FileTableTabs.java:73)
 at com.mucommander.ui.main.tabs.FileTableTabs.selectTab(FileTableTabs.java:68)
 at com.mucommander.ui.main.FolderPanel.<init>(FolderPanel.java:177)
 at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:286)
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.createMainFrame(DefaultMainFramesBuilder.java:112)
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.build(DefaultMainFramesBuilder.java:83)
 at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:166)
 at com.mucommander.muCommander.run(muCommander.java:512)
 at com.mucommander.muCommander.main(muCommander.java:275)
```

**Comment by zlobjc** [comment]
some thing wrong with US localization <language>en</language>
with <language>en_GB</language> works well

**Comment by ahadas** [comment]
@zlobjc , can you please be more specific about what is wrong with the US localocation?

**Comment by zlobjc** [comment]
At the first success launch UI was localized as OS default(non US) but in preferences Language was English. and `<language>en</language>` in file.
I try to switch to different language and restart, it's works as expected.
And when switch to english and restart, but again UI language was OS language.
When I edit preferences.xml and set `en_GB` and it's works.
Now I can't reproduce that :(

**Comment by ahadas** [comment]
@zlobjc sorry for taking me so long to get to this, does it still happen?

**Comment by ahadas** [comment]
@zlobjc , thanks for reporting this! there was a bug, caused when upgrading the jna library that we use in some cases when checking for system files on windows. I'll probably release another version of 0.9.2 with this fix and a fix for the delete to trash that was also broken. In the meantime, you can edit the properties.xml file and set ```<show_system_folders>true</show_system_folders>``` or edit the snapshot.xml file and remove the ```windows``` element. Note that if you choose the second option, that exception will still happen when you browse the folder that your application was started with before.

**Comment by zlobjc** [comment]
> @zlobjc sorry for taking me so long to get to this, does it still happen?
no, it's was been just one time. I just remove settings folder

**Comment by ahadas** [comment]
It would probably happen again if, for example, you browse c:\ and then quite muCommander. 
Right, removing the settings folder can also solve it. This is a bit aggressive solution though because you lose all your bookmarks and other stuff.

**Comment by lord-alfred** [comment]
On MacOSX:

java.lang.ExceptionInInitializerError
 at com.mucommander.ui.event.LocationManager.<init>(LocationManager.java:63)
 at com.mucommander.ui.main.FolderPanel.<init>(FolderPanel.java:89)
 at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:286)
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.createMainFrame(DefaultMainFramesBuilder.java:112)
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.build(DefaultMainFramesBuilder.java:83)
 at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:166)
 at com.mucommander.muCommander.run(muCommander.java:512)
 at com.mucommander.muCommander.main(muCommander.java:275)
Caused by: java.lang.NullPointerException
 at com.mucommander.commons.file.FileURL.getFileURL(FileURL.java:215)
 at com.mucommander.core.GlobalLocationHistory.<init>(GlobalLocationHistory.java:72)
 at com.mucommander.core.GlobalLocationHistory.<clinit>(GlobalLocationHistory.java:53)
 ... 8 more
