### ISSUE TITLE
Avoid using log4j 1.x

### ISSUE THREAD

**Issue by gladko** [mucommander/mucommander#1084]
### Description

Hi team. 
Thanks for great app!
I faced with the following issue: security guard installed on my laptop does not allow to use vulnerable or not supported code. Since  Log4j 1.x has reached End of live in 2015 and is no longer supported, the guard removes bundle/log4j-1.2.17.jar file and breaks mucommander.
Let's migrate to  log4j 2.x and makes the security guard happy.

log:
```
$ ./mucommander.sh; exit
No config.properties found.
ERROR: Bundle jetbrains-jediterm [41] Error starting file:/Users/xxx/Applications/mucommander-1.3.0-1-portable/bundle/jetbrains-jediterm-1.3.0.jar (org.osgi.framework.BundleException: Unable to resolve jetbrains-jediterm [41](R 41.0): missing requirement [jetbrains-jediterm [41](R 41.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.log4j)(version>=1.2.0)(!(version>=2.0.0))) Unresolved requirements: [[jetbrains-jediterm [41](R 41.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.log4j)(version>=1.2.0)(!(version>=2.0.0)))])
org.osgi.framework.BundleException: Unable to resolve jetbrains-jediterm [41](R 41.0): missing requirement [jetbrains-jediterm [41](R 41.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.log4j)(version>=1.2.0)(!(version>=2.0.0))) Unresolved requirements: [[jetbrains-jediterm [41](R 41.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.log4j)(version>=1.2.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
	at java.base/java.lang.Thread.run(Thread.java:834)
ERROR: Bundle mucommander-bonjour [56] Error starting file:/Users/xxx/Applications/mucommander-1.3.0-1-portable/bundle/mucommander-bonjour-1.3.0.jar (org.osgi.framework.BundleException: Unable to resolve mucommander-bonjour [56](R 56.0): missing requirement [mucommander-bonjour [56](R 56.0)] osgi.wiring.package; (&(osgi.wiring.package=com.mucommander.ui.action)(version>=1.3.0)(!(version>=2.0.0))) [caused by: Unable to resolve mucommander-core [115](R 115.0): missing requirement [mucommander-core [115](R 115.0)] osgi.wiring.package; (osgi.wiring.package=com.jediterm.core.util) [caused by: Unable to resolve jetbrains-jediterm [41](R 41.0): missing requirement [jetbrains-jediterm [41](R 41.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.log4j)(version>=1.2.0)(!(version>=2.0.0)))]] Unresolved requirements: [[mucommander-bonjour [56](R 56.0)] osgi.wiring.package; (&(osgi.wiring.package=com.mucommander.ui.action)(version>=1.3.0)(!(version>=2.0.0)))])
org.osgi.framework.BundleException: Unable to resolve mucommander-bonjour [56](R 56.0): missing requirement [mucommander-bonjour [56](R 56.0)] osgi.wiring.package; (&(osgi.wiring.package=com.mucommander.ui.action)(version>=1.3.0)(!(version>=2.0.0))) [caused by: Unable to resolve mucommander-core [115](R 115.0): missing requirement [mucommander-core [115](R 115.0)] osgi.wiring.package; (osgi.wiring.package=com.jediterm.core.util) [caused by: Unable to resolve jetbrains-jediterm [41](R 41.0): missing requirement [jetbrains-jediterm [41](R 41.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.log4j)(version>=1.2.0)(!(version>=2.0.0)))]] Unresolved requirements: [[mucommander-bonjour [56](R 56.0)] osgi.wiring.package; (&(osgi.wiring.package=com.mucommander.ui.action)(version>=1.3.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
	at java.base/java.lang.Thread.run(Thread.java:834)
2023-11-27 22:08:07.410 [FelixStartLevel] INFO  c.m.commons.runtime.OsFamily:70 - Current OS family: macOS
2023-11-27 22:08:07.414 [FelixStartLevel] INFO  c.m.commons.runtime.OsFamily:71 - Current OS version: 10.16
```

**Comment by gladko** [comment]
created a PR: https://github.com/mucommander/mucommander/pull/1085
