### ISSUE TITLE
Deleting to Trash not working in Windows 7

### ISSUE THREAD

**Issue by xmirog** [mucommander/mucommander#109]
I have mucommander 0.9.2, Java 8 and Windows 7-64bit. When I try to delete files and the "Move to trash" option is checked, the dialog of "Deleting" appears, but nothing happens (the dialog must be closed manually and the file is not moved to trash). In the console there is an error message:

_Exception in thread "Thread-7" java.lang.Error: Structure.getFieldOrder() on class com.mucommander.commons.file.util.She
ll32API$SHFILEOPSTRUCT does not provide enough names ([fAnyOperationsAborted, fFlags, hwnd, lpszProgressTitle, pFrom, pN
ameMappings, pTo, wFunc]) to match declared fields ([fFlags, pFrom, wFunc])
        at com.sun.jna.Structure.getFields(Structure.java:913)
        at com.sun.jna.Structure.deriveLayout(Structure.java:1058)
        at com.sun.jna.Structure.calculateSize(Structure.java:982)
        at com.sun.jna.Structure.allocateMemory(Structure.java:363)
        at com.sun.jna.Structure.ensureAllocated(Structure.java:339)
        at com.sun.jna.Structure.ensureAllocated(Structure.java:329)
        at com.sun.jna.Structure.write(Structure.java:701)
        at com.sun.jna.Structure.autoWrite(Structure.java:1923)
        at com.sun.jna.Function.convertArgument(Function.java:505)
        at com.sun.jna.Function.invoke(Function.java:297)
        at com.sun.jna.Library$Handler.invoke(Library.java:212)
        at com.sun.proxy.$Proxy3.SHFileOperation(Unknown Source)
        at com.mucommander.desktop.windows.WindowsTrash.moveToTrash(WindowsTrash.java:148)
        at com.mucommander.desktop.QueuedTrash$MoveToTrashThread.run(QueuedTrash.java:149)_

This functionality works with the same hardware and version of JDK with mucommander 0.9.1.

**Comment by ahadas** [comment]
@xmirog thanks for reporting! I found the problem. I will publish a new release of 0.9.2 soon with the fix.

**Comment by xmirog** [comment]
Thank you for this quick solution, Arik. Glad to know that there will be a release soon with the fix.

**Comment by tomaszwojciechowski** [comment]
This bug still exists on Windows 7. Deleting without trash works fine.

**Comment by ahadas** [comment]
Yeah, the fix has not been released yet (sorry for the earlier promise). It will hopefully be released soon.

**Comment by SGvagon** [comment]
> 
> 
> Yeah, that's because the fix has not been released yet (sorry for the earlier promise). It will hopefully be released soon.

So, moving to trash still not working in Windows 7 , and I use 0.9.2 version :-/ .

**Comment by ahadas** [comment]
@SGvagon Right, sorry about that.  The plan was to introduce initial support for plugins in the next version but that takes longer than I thought. I think we have enough fixes on the master branch now to release the next version and postpone the pluggable design for the next one.

**Comment by SGvagon** [comment]
> 
> 
> @SGvagon Right, sorry about that. The plan was to introduce initial support for plugins in the next version but that takes longer than I thought. I think we have enough fixes on the master branch now to release the next version and postpone the pluggable design for the next one.

On now in 0.9.3 move to trash working, but whe I try remove for example Nvidia folder on C:\ , it shows error table, some files cannot be removed. This folder created by Nvidia, so maybe MuCommander doesn't have permission for delete that folder? Permanent delete not working on this folder too.

**Comment by ahadas** [comment]
@SGvagon Thanks for confirming that the fix works in the general case.  As for the inability to remove the Nvidia folder, let's discuss it in #173 .
