### ISSUE TITLE
[Bug] Problem connecting to SMB share

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#1140]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

Using muCommander, I tried to connect to an SMB share that I'd just connected to using Finder, and got an error box telling me "Unable to read content... Access is denied"

### Steps to reproduce

Go to Go -> Connect to server

Select SMB

Server: idrives.haas.berkeley.edu
Share: rhstanton$

Then add name and password and click "Connect"

### Expected behavior

Network drive should show up in muCommander

### Actual behavior

Error box telling me "Unable to read content... Access is denied". Details tell me:

java.lang.RuntimeException: Access is denied.
 at com.mucommander.ui.event.LocationManager.setCurrentFolder(LocationManager.java:104)
 at com.mucommander.core.LocationChanger.setCurrentFolder(LocationChanger.java:352)
 at com.mucommander.core.BrowseLocationThread.run(BrowseLocationThread.java:381)

### muCommander version

1.3.0

### Java version

Runtime version: 20
VM name: OpenJDK 64-Bit Server VM
VM version: 20+36
VM vendor: Eclipse Adoptium

### Operating System type and version

Name: Mac OS X
Version: 12.7.4
Architecture: x86_64

### Relevant log output

```shell
[2024-04-02 11:58:32.134] FINE SmbTransportImpl.java#getSmbSession,398 Establishing new session SmbSession[credentials=rhstanton,targetHost=idrives.haas.berkeley.edu,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport1

[2024-04-02 11:58:32.134] FINEST SmbSessionImpl.java#acquire,177 Acquire session 2 SmbSession[credentials=rhstanton,targetHost=idrives.haas.berkeley.edu,targetDomain=null,uid=0,connectionState=0,usage=2]

[2024-04-02 11:58:32.134] FINEST SmbTreeImpl.java#acquire,163 Acquire tree 1 SmbTree[share=RHSTANTON$,service=?????,tid=-1,inDfs=false,inDomainDfs=false,connectionState=0,usage=1]

[2024-04-02 11:58:32.134] FINEST SmbTreeConnection.java#connectTree,612 doConnect: idrives.haas.berkeley.edu

[2024-04-02 11:58:32.134] FINEST SmbSessionImpl.java#acquire,177 Acquire session 3 SmbSession[credentials=rhstanton,targetHost=idrives.haas.berkeley.edu,targetDomain=null,uid=0,connectionState=0,usage=3]

[2024-04-02 11:58:32.135] FINEST Transport.java#acquire,109 Acquire transport 3 Transport1[idrives.haas.berkeley.edu/169.229.215.71:445,state=3,signingEnforced=false,usage=3]

[2024-04-02 11:58:32.135] FINE SmbTreeImpl.java#treeConnect,560 Connection state was 0

[2024-04-02 11:58:32.135] FINE SmbTreeImpl.java#treeConnect,591 treeConnect: unc=\\idrives.haas.berkeley.edu\RHSTANTON$,service=?????

[2024-04-02 11:58:32.135] FINEST Transport.java#acquire,109 Acquire transport 4 Transport1[idrives.haas.berkeley.edu/169.229.215.71:445,state=3,signingEnforced=false,usage=4]

[2024-04-02 11:58:32.135] FINEST Transport.java#acquire,109 Acquire transport 5 Transport1[idrives.haas.berkeley.edu/169.229.215.71:445,state=3,signingEnforced=false,usage=5]

[2024-04-02 11:58:32.135] FINE SmbSessionImpl.java#sessionSetup,479 sessionSetup: rhstanton

[2024-04-02 11:58:32.135] FINE SmbSessionImpl.java#createContext,702 Remote host is idrives.haas.berkeley.edu

[2024-04-02 11:58:32.135] FINE NtlmPasswordAuthenticator.java#createContext,245 Have initial token NegTokenInit[flags=0,mechs=[1.3.6.1.4.1.311.2.2.30, 1.2.840.48018.1.2.2, 1.2.840.113554.1.2.2, 1.2.840.113554.1.2.2.3, 1.3.6.1.4.1.311.2.2.10],mic=null]

[2024-04-02 11:58:32.136] FINEST NtlmContext.java#makeNegotiate,336 Type1Message[suppliedDomain=,suppliedWorkstation=null,flags=0x62088215]

[2024-04-02 11:58:32.136] FINEST NtlmContext.java#makeNegotiate,337 4E544C4D53535000010000001582086200000000280000000000000028000000060100000000000F

[2024-04-02 11:58:32.136] FINEST SmbTransportImpl.java#send,1536 Sending command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0

[2024-04-02 11:58:32.136] FINE FolderChangeMonitor.java#windowGainedFocus,323 com.mucommander.core.FolderChangeMonitor@e394bd8: setting forceRefresh as MainFrame gained focus

[2024-04-02 11:58:32.136] FINEST SmbTransportImpl.java#sendrecv,958 jcifs.internal.smb2.session.Smb2SessionSetupRequest costs 1 avail 1 (Transport1)

[2024-04-02 11:58:32.137] FINEST SmbTransportImpl.java#sendrecv,1015 Request credits 512

[2024-04-02 11:58:32.137] FINEST SmbTransportImpl.java#sendrecv,1023 Sending command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0

[2024-04-02 11:58:32.137] FINEST SmbTransportImpl.java#doSend,903 command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=2,wordCount=0,byteCount=98

[2024-04-02 11:58:32.137] FINEST SmbTransportImpl.java#doSend,906 FE534D4240000000000000000100000200000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000019000001000000000000000058004A000000000000000000604806062B0601050502A03E303CA00E300C060A2B06010401823702020AA22A04284E544C4D53535000010000001582086200000000280000000000000028000000060100000000000F000000000000

[2024-04-02 11:58:32.145] FINEST SmbTransportImpl.java#peekKey,839 New data read: Transport1[idrives.haas.berkeley.edu/169.229.215.71:445,state=3,signingEnforced=false,usage=5]

[2024-04-02 11:58:32.145] FINEST SmbTransportImpl.java#peekKey,840 FE534D4240000000160000C00100010001000000000000000200000000000000

[2024-04-02 11:58:32.145] FINE SmbTransportImpl.java#sendrecv,1029 Breaking on error command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0001,mid=2,wordCount=0,byteCount=0

[2024-04-02 11:58:32.146] FINEST SmbTransportImpl.java#sendrecv,1073 Adding credits 1

[2024-04-02 11:58:32.146] FINEST SmbTransportImpl.java#send,1560 Response is command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0001,mid=2,wordCount=0,byteCount=0

[2024-04-02 11:58:32.146] FINEST NtlmContext.java#makeAuthenticate,251 Type2Message[target=CAMPUS,challenge=<8 bytes>,context=null,targetInformation=<184 bytes>,flags=0x62898215]

[2024-04-02 11:58:32.146] FINEST NtlmContext.java#makeAuthenticate,252 

[deleted from here on as I can't tell if anything might contain sensitive information]
```

**Comment by pskowronek** [comment]
Yup, maybe not exactly the same scenario, but I wasn't able to use SMB ever in muC :)
I think smb support requires more love (like to be able to browse smb network), @ahadas any thoughts on that?

**Comment by rhstanton** [comment]
I was wondering if it was just the dollar sign in the share name, but it sounds like it may be something more fundamental.

**Comment by ShayArtzi** [comment]
I have tried to access password protected SMB shares with and without `$` sign in the name and for me all those cases actually seems to be working. My setup is a bit different since I'm on windows, but IMO it shouldn't matter since the SMB client seems to be a native java one.

@rhstanton do you know anything about the server you are connecting to? Which OS is used there (is it a windows machine or samba on linux etc), what version of SMB is used etc? anything that might help recreate this issue locally.

Also, I know you removed some of the logs because of security concerns but I suspect the data there might help identifying the problem - are you able to somehow sanitize it for sensitive information and share it here?

**Comment by rhstanton** [comment]
I'll see what I can find out about the server. 

Meanwhile, I’d be happy to share more information but I don’t know whether there’s sensitive info there or not (if I saw my password in plan text, that would be easy(!), but there’s lots of back and forth containing data that isn’t plain text, and I don’t know what it actually does contain when appropriately decoded).

I just tried again on my work machine, where the debug level is set to WARNING rather than FINEST. Here I see

    • [2024-04-03 12:15:51.583] SEVERE AdbUtils.java#getDevices,62 failed to list android devices

Is that  useful?

**Comment by rhstanton** [comment]
Actually I can't be sure that message was related to the SMB connection. Here is the debug log set to FINE:

[2024-04-03 12:22:03.296] FINE Transport.java#loop,438 Idle timeout on Transport2
[2024-04-03 12:22:03.297] FINE Transport.java#loop,473 socket timeout in non peek state
[2024-04-03 12:22:03.297] FINE SmbTransportImpl.java#doDisconnect,769 Disconnecting transport Transport2[idrives.haas.berkeley.edu/169.229.215.71:445,state=5,signingEnforced=false,usage=0]
[2024-04-03 12:22:03.298] FINE SmbTransportPoolImpl.java#removeTransport,264 Scheduling transport connection for removal Transport2[idrives.haas.berkeley.edu/169.229.215.71:445,state=5,signingEnforced=false,usage=0] (271613892)
[2024-04-03 12:22:03.298] FINE Transport.java#loop,487 Disconnected
[2024-04-03 12:22:03.298] FINE Transport.java#loop,502 Exception without a request pending
[2024-04-03 12:22:20.679] FINE FolderChangeMonitor.java#windowGainedFocus,323 com.mucommander.core.FolderChangeMonitor@7bb1f8d0: setting forceRefresh as MainFrame gained focus
[2024-04-03 12:22:20.853] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false
[2024-04-03 12:22:20.854] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false
[2024-04-03 12:22:27.330] FINE SkopeoCommandExecutor.java#execute,96 Executing skopeo command: 
[2024-04-03 12:22:27.334] FINE SkopeoCommandExecutor.java#execute,127 Unexcepted exception while executing skopeo
[2024-04-03 12:22:27.459] FINE FocusRequester.java#run,102 focus requested on com.mucommander.commons.file.protocol.smb.SMBPanel
[2024-04-03 12:22:29.250] FINE LocationChanger.java#tryChangeCurrentFolder,273 folderURL=smb://idrives.haas.berkeley.edu/rhstanton$
[2024-04-03 12:22:29.251] FINE BrowseLocationThread.java#run,155 starting folder change...
[2024-04-03 12:22:29.252] FINE NameServiceClientImpl.java#getAllByName,1022 Resolved 'idrives.haas.berkeley.edu' to [idrives.haas.berkeley.edu/169.229.215.71] using DNS
[2024-04-03 12:22:29.253] FINE SmbTransportPoolImpl.java#getSmbTransport,216 Trying address idrives.haas.berkeley.edu/169.229.215.71
[2024-04-03 12:22:29.253] FINE SmbTransportPoolImpl.java#cleanup,276 Removing transport connection Transport2[idrives.haas.berkeley.edu/169.229.215.71:445,state=6,signingEnforced=false,usage=0] (271613892)
[2024-04-03 12:22:29.253] FINE SmbTransportPoolImpl.java#getSmbTransport,96 New transport connection Transport3[idrives.haas.berkeley.edu/169.229.215.71:445,state=0,signingEnforced=false,usage=1]
[2024-04-03 12:22:29.253] FINE Transport.java#connect,578 Connecting Transport3
[2024-04-03 12:22:29.253] FINE SmbTransportImpl.java#doConnect,701 Connecting in state 1 addr 169.229.215.71
[2024-04-03 12:22:29.259] FINE SmbTransportImpl.java#doConnect,725 Negotiation response on Transport3 :jcifs.internal.SmbNegotiation@42150ebb
[2024-04-03 12:22:29.259] FINE SmbTransportImpl.java#doConnect,735 Signature negotiation enforced false (server false) enabled false (server true)
[2024-04-03 12:22:29.260] FINE SmbTransportImpl.java#getSmbSession,398 Establishing new session SmbSession[credentials=rhstanton,targetHost=idrives.haas.berkeley.edu,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport3
[2024-04-03 12:22:29.260] FINE SmbTreeImpl.java#treeConnect,560 Connection state was 0
[2024-04-03 12:22:29.260] FINE SmbTreeImpl.java#treeConnect,591 treeConnect: unc=\\idrives.haas.berkeley.edu\RHSTANTON$,service=?????
[2024-04-03 12:22:29.260] FINE SmbSessionImpl.java#sessionSetup,479 sessionSetup: rhstanton
[2024-04-03 12:22:29.260] FINE SmbSessionImpl.java#createContext,702 Remote host is idrives.haas.berkeley.edu
[2024-04-03 12:22:29.260] FINE NtlmPasswordAuthenticator.java#createContext,245 Have initial token NegTokenInit[flags=0,mechs=[1.3.6.1.4.1.311.2.2.30, 1.2.840.48018.1.2.2, 1.2.840.113554.1.2.2, 1.2.840.113554.1.2.2.3, 1.3.6.1.4.1.311.2.2.10],mic=null]
[2024-04-03 12:22:29.262] FINE SmbTransportImpl.java#sendrecv,1029 Breaking on error command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0001,mid=2,wordCount=0,byteCount=0
[2024-04-03 12:22:29.263] FINE NtlmContext.java#initSessionSecurity,350 Sign key is [deleted]
[2024-04-03 12:22:29.263] FINE NtlmContext.java#initSessionSecurity,351 Verify key is [deleted]
[2024-04-03 12:22:29.263] FINE NtlmContext.java#initSessionSecurity,357 Seal key is [deleted]
[2024-04-03 12:22:29.263] FINE NtlmContext.java#initSessionSecurity,364 Server seal key is [deleted]
[2024-04-03 12:22:29.263] FINE NtlmContext.java#calculateMIC,409 Digest [deleted]
[2024-04-03 12:22:29.263] FINE NtlmContext.java#calculateMIC,410 Truncated [deleted]
[2024-04-03 12:22:29.263] FINE NtlmContext.java#calculateMIC,417 Encrypted  [deleted]
[2024-04-03 12:22:29.264] FINE SpnegoContext.java#calculateMechListMIC,321 Out Mech list [1.3.6.1.4.1.311.2.210]
[2024-04-03 12:22:29.264] FINE SpnegoContext.java#calculateMechListMIC,322 Out Mech list encoded [deleted]
[2024-04-03 12:22:29.264] FINE SpnegoContext.java#calculateMechListMIC,323 Out Mech list MIC [deleted]
[2024-04-03 12:22:29.267] FINE FolderChangeMonitor.java#windowGainedFocus,323com.mucommander.core.FolderChangeMonitor@7bb1f8d0: setting forceRefresh as MainFrame gained focus
[2024-04-03 12:22:29.283] FINE SmbSessionImpl.java#sessionSetup,498 Session setup failed
[2024-04-03 12:22:29.283] FINE SmbTreeImpl.java#treeConnect,634 Disconnect tree on treeConnectFailure
[2024-04-03 12:22:29.283] FINE SmbTreeConnection.java#connectTree,618 Authentication failed
[2024-04-03 12:22:29.283] FINE SmbTreeImpl.java#release,217 Usage dropped to zero, release session
[2024-04-03 12:22:29.283] FINE SmbSessionImpl.java#release,228 Usage dropped to zero, release connection Transport3[idrives.haas.berkeley.edu/169.229.215.71:445,state=3,signingEnforced=false,usage=2]
[2024-04-03 12:22:29.283] FINE SmbTreeConnection.java#connectHost,581 Referral failed, trying next
[2024-04-03 12:22:29.283] INFO SMBFile.java#exists,292 Exception caught while calling SmbFile#exists(): Logon failure: unknown user name or bad password.
[2024-04-03 12:22:29.284] FINE NameServiceClientImpl.java#getAllByName,1022 Resolved 'idrives.haas.berkeley.edu' to [idrives.haas.berkeley.edu/169.229.215.71] using DNS
[2024-04-03 12:22:29.284] FINE SmbSessionImpl.java#acquire,183 Reacquire transport
[2024-04-03 12:22:29.284] FINE SmbTreeImpl.java#acquire,175 Reacquire session
[2024-04-03 12:22:29.284] FINE SmbTreeImpl.java#treeConnect,560 Connection state was 0
[2024-04-03 12:22:29.284] FINE SmbTreeImpl.java#treeConnect,591 treeConnect: unc=\\idrives.haas.berkeley.edu\RHSTANTON$,service=?????
[2024-04-03 12:22:29.284] FINE SmbSessionImpl.java#sessionSetup,479 sessionSetup: rhstanton
[2024-04-03 12:22:29.284] FINE SmbSessionImpl.java#createContext,702 Remote host is idrives.haas.berkeley.edu
[2024-04-03 12:22:29.284] FINE NtlmPasswordAuthenticator.java#createContext,245 Have initial token NegTokenInit[flags=0,mechs=[1.3.6.1.4.1.311.2.2.30, 1.2.840.48018.1.2.2, 1.2.840.113554.1.2.2, 1.2.840.113554.1.2.2.3, 1.3.6.1.4.1.311.2.2.10],mic=null]
[2024-04-03 12:22:29.286] FINE SmbTransportImpl.java#sendrecv,1029 Breaking on error command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0001,mid=4,wordCount=0,byteCount=0
[2024-04-03 12:22:29.287] FINE NtlmContext.java#initSessionSecurity,350 Sign key is [deleted]
[2024-04-03 12:22:29.287] FINE NtlmContext.java#initSessionSecurity,351 Verify key is [deleted]
[2024-04-03 12:22:29.287] FINE NtlmContext.java#initSessionSecurity,357 Seal key is [deleted]
[2024-04-03 12:22:29.287] FINE NtlmContext.java#initSessionSecurity,364 Server seal key is [deleted]
[2024-04-03 12:22:29.287] FINE NtlmContext.java#calculateMIC,409 Digest [deleted]
[2024-04-03 12:22:29.287] FINE NtlmContext.java#calculateMIC,410 Truncated [deleted]
[2024-04-03 12:22:29.287] FINE NtlmContext.java#calculateMIC,417 [deleted]
[2024-04-03 12:22:29.287] FINE SpnegoContext.java#calculateMechListMIC,321 Out Mech list [1.3.6.1.4.1.311.2.2.10]
[2024-04-03 12:22:29.287] FINE SpnegoContext.java#calculateMechListMIC,322 Out Mech list encoded [deeted]
[2024-04-03 12:22:29.287] FINE SpnegoContext.java#calculateMechListMIC,323 Out Mech list MIC [deleted]
[2024-04-03 12:22:29.303] FINE SmbSessionImpl.java#sessionSetup,498 Session setup failed
[2024-04-03 12:22:29.303] FINE SmbTreeImpl.java#treeConnect,634 Disconnect tree on treeConnectFailure
[2024-04-03 12:22:29.303] FINE SmbTreeConnection.java#connectTree,618 Authentication failed
[2024-04-03 12:22:29.304] FINE SmbTreeImpl.java#release,217 Usage dropped to zero, release session
[2024-04-03 12:22:29.304] FINE SmbSessionImpl.java#release,228 Usage dropped to zero, release connection Transport3[idrives.haas.berkeley.edu/169.229.215.71:445,state=3,signingEnforced=false,usage=2]
[2024-04-03 12:22:29.304] FINE SmbTreeConnection.java#connectHost,581 Referral failed, trying next
[2024-04-03 12:22:29.304] FINE LocationManager.java#setCurrentFolder,94 Couldn't ls children of smb://idrives.haas.berkeley.edu/rhstanton$/, error: Logon failure: unknown user name or bad password.
[2024-04-03 12:22:29.304] FINE BrowseLocationThread.java#run,398 Caught exception
[2024-04-03 12:22:29.309] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false
[2024-04-03 12:22:29.426] FINE FocusRequester.java#run,102 focus requested on javax.swing.JButton
[2024-04-03 12:22:30.729] FINE FolderChangeMonitor.java#windowGainedFocus,323 com.mucommander.core.FolderChangeMonitor@7bb1f8d0: setting forceRefresh as MainFrame gained focus
[2024-04-03 12:22:30.820] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false
[2024-04-03 12:22:30.820] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false

**Comment by ShayArtzi** [comment]
Consider the following line from the log above:
```[2024-04-03 12:22:29.283] INFO SMBFile.java#exists,292 Exception caught while calling SmbFile#exists(): Logon failure: unknown user name or bad password.```

Are you able to access the same share using some other SMB client? I guess you do provide username and password in the UI, right?

I'm just trying to gather as many details as I can to try and recreate this scenario locally so I'm able to debug

**Comment by rhstanton** [comment]
I see this line above:

[2024-04-03 12:22:29.260] FINE SmbTreeImpl.java#treeConnect,591 treeConnect: unc=\idrives.haas.berkeley.edu\RHSTANTON$,service=?????

The upper-case RHSTANTON$ looks a bit suspicious to me.

**Comment by ShayArtzi** [comment]
Could you please try to connect without specifying the share name (leave the field blank) and report back?

**Comment by rhstanton** [comment]
That connects fine! muCommander shows a panel for smb://idrives.haas.berkeley.edu/, and inside are some directories whose names correspond to various shares (names followed by dollar signs).

BUT, while this is hopefully useful for debugging purposes, my name isn't one of the shares listed, so I can't use this as a work-around to my original problem.

By the way, I tried the same thing using macOS Finder. A box popped up asking me which volumes I wanted to mount on idrives.haas.berkeley.edu", but the box didn't show any names at all.

**Comment by ShayArtzi** [comment]
That's interesting - as far as I know, in SMB a dollar sign at the end of a share name makes a specific share "hidden" so its actually not listed. In your case it sounds like some shares that ends with `$` are actually listed, but some others (including yours) are not.

At this point I think we will need to get more details about the server you are using - what SMB server software does it run, what version etc. Any details you are able to get can help.

And just to confirm - when you try macOS finder with the same host while specifying your personal share - it does work. correct?

Some more background: muCommander is using a library called `jcifs-ng` for interacting with SMB. I just verified that we are using the latest version if the library (2.17).

**Comment by rhstanton** [comment]
I'll see what I can find out. 

And yes, Finder + share - specified as **smb://idrives.haas.berkeley.edu/rhstanton$** - works just fine.

**Comment by ShayArtzi** [comment]
Another thing I'm thinking about - looks like this is some university share. Don't you also need to include the domain name while connecting? Typically on windows it will be something like `DOMAIN\username` but in muC there is a special field for that in the SMB dialog

**Comment by rhstanton** [comment]
I think there are various ways of specifying the share. In muCommander, I ask to connect to a server, select the SMB tab, then enter the relevant details. At the bottom it tells me what server URL it's using, and it ends up being the same as I pass directly to Finder, smb://idrives.haas.berkeley.edu/rhstanton$

**Comment by rhstanton** [comment]
Also, remember that it connected OK when I didn't specify a particular share, so it _can_ connect this way.

**Comment by ShayArtzi** [comment]
I was referring to the windows domain + username combination (assuming the server is windows), and not to the URL:
![image](https://github.com/mucommander/mucommander/assets/7936008/118eed87-a1dc-4bb8-b84b-da0315e8e4c8)

**Comment by rhstanton** [comment]
Not sure. I've just left the domain field blank.

**Comment by ShayArtzi** [comment]
that might be a long shot, but: https://berkeley.service-now.com/kb_view.do?sys_kb_id=e039735c1b1759500284ca2b234bcbe1

according to this page the domain name is `CAMPUS`. Again - long shot, IDK if it is relevant or updated at all

**Comment by rhstanton** [comment]
> that might be a long shot, but: https://berkeley.service-now.com/kb_view.do?sys_kb_id=e039735c1b1759500284ca2b234bcbe1
> 
> according to this page the domain name is `CAMPUS`. Again - long shot, IDK if it is relevant or updated at all

I tried adding CAMPUS as the domain, and got the same result as before.

**Comment by ShayArtzi** [comment]
> This is weird. When I click on the muC "Go" menu item, down at the bottom one of the options is **rhstanton$**
> 
> When I select this, muC opens a panel showing the contents of directory **/Volumes/rhstanton$**, and it's showing me (correctly) the contents of the share I'm looking for.
> 
> Could all this be because muC doesn't like being asked to open a share twice, or is something else going on? Either way, this does give me options that allow me to do what I'm trying to do.

I think you might have mounted the SMB via finder and because of that it is listed under `/Volumes`, so the mount is accessible by muC but is initiated by the OS

**Comment by rhstanton** [comment]
I think that's right. But unmounting it doesn't help with the muC problem.

**Comment by rhstanton** [comment]
Some info on the server:

"Your iDrive is hosted on a Windows Server 2016 VM. Windows Server 2016 supports SMB version 3.1.1 by default."

**Comment by rhstanton** [comment]
By the way, the IT guy who gave me this information also offered to set up a Zoom meeting with you, @ShayArtzi, to help with troubleshooting.

**Comment by ShayArtzi** [comment]
Okay, so I'm not sure muC supports SMB v3 currently. I'll have to look into that. I don't mind taking to this IT guy, they might be able to provide some test credentials if the share is public, or else provide more details on the environment.

**Comment by rhstanton** [comment]
Great. If you give me your email address, I’ll pass it on to him.

Thanks!

**Comment by ShayArtzi** [comment]
sure, its shay@artzi.org

**Comment by ShayArtzi** [comment]
Okay, I have some news regarding this issue - after talking to Charles from Berkeley's IT I was able to figure it out.

The problem is reproduced when `Encrypt data access` is enabled:
![image](https://github.com/mucommander/mucommander/assets/7936008/839900d4-9095-4bc7-90dc-74df127d1299)

When I disable this option (like shown in the screenshot), I'm able to access the share from muC. I can also conform this issue is not os dependent as I was using a windows machine to run muC.

Unfortunately it seems like data encryption is not supported by `jcifs-ng` (according to [this issue](https://github.com/AgNO3/jcifs-ng/issues/356)).

**Comment by rhstanton** [comment]
That's great that you were able to pinpoint the problem exactly. Slightly less great that it's not something you can fix right now, but at least we know it's not a bug in the muC code. I appreciate all the effort you've put into this, and for me it just means I'll connect using Finder and then point muC at /Volumes/rhstanton$.

**Comment by ShayArtzi** [comment]
Sounds good. I'm now watching `jcifs-ng` releases, and if they will release a version that supports SMB encryption I'm happy to create a PR to include it in a future version of muC.

**Comment by jbostoen** [comment]
Is there any progress on this, please?

**Comment by ShayArtzi** [comment]
> Is there any progress on this, please?

Hi @jbostoen,

Unfortunately, the answer is no. 
The root cause for this issue is an open-source library we are using (`jcifs-ng`), which have yet to add support for the use case in question. We are already using the latest version of this library, which was [released on October 2023](https://github.com/AgNO3/jcifs-ng/releases/tag/jcifs-ng-2.1.10).

The way I see it, we have to options:
1. Keep on waiting until the root cause is fixed. Just like muCommander, `jcifs-ng` is an open source project maintained by volunteers, which means we don't have an expected timeline for this fixed.
2. Re-implement SMB support using another library (like [smbj](https://github.com/hierynomus/smbj)). This will require a significant amount of work, which personally I cannot commit to right now (that might change in the future).

In the meantime, one workaround you could potentially use is SMB share mapping/mounting via your operating system. Once your SMB share is represented as a drive (in windows) or mount (in unix-like systems) it will be treated like any other drive/directory on your machine.
