### ISSUE TITLE
[Bug] "muCommander" freezes at the initialization stage at the first start.

### ISSUE THREAD

**Issue by demetriuzz** [mucommander/mucommander#1182]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

Initialization window _freezes_ when `muCommander` start **first** time: when user enter name+password and run new session in `XFCE`.

### Steps to reproduce

It's not _easy_. We need to start a new session.

### Expected behavior

Need _expected_ process - run and work program.

### Actual behavior

First you need to _kill_ the `X window`: instance of `muCommander`.
Then again run `muCommander`.
But _sometimes_ you need to kill the startup window **twice**.

### Screenshots?

![изображение](https://github.com/mucommander/mucommander/assets/61899867/795b0b40-be79-49c1-ae11-3184e9c56202)
And no more ...

### muCommander version

version `1.4.0` from installed `mucommander_1.4.0_amd64.deb`.
(Build date: 2024/05/02
 Build number: a470208)

### Java version

`Java` version embedded in `muCommander`
```text
Runtime version: 23-internal
VM name: OpenJDK 64-Bit Server VM
VM version: 23-internal-ahadas-737c9028db3d95512c25dc620d5a11dcec087f91
VM vendor: Oracle Corporation
```
`Java` version on host:
```text
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment (build 17.0.11+9-Debian-1deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.11+9-Debian-1deb12u1, mixed mode, sharing)
```

### Operating System type and version

`XFCE 4.18`
on Linux Debian `12.5`
`Linux 6.1.0-20-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64 GNU/Linux`

### Relevant log output

```shell
Log info from console (form file `.xsession-errors` in home directory):

[muEpoch+2217ms] muCommander: OSGi framework with muC fully started
Exception in thread "MainFrameInit" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 4
        at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:317)
        at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.createMainFrame(DefaultMainFramesBuilder.java:121)
        at java.base/java.util.stream.IntPipeline$1$1.accept(Unknown Source)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.Spliterator$OfInt.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.build(DefaultMainFramesBuilder.java:67)
        at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:207)
        at com.mucommander.Application.lambda$run$12(Application.java:498)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 4
        at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
        at com.mucommander.ui.main.MainFrame.init(MainFrame.java:185)
        at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:315)
        ... 13 more
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 4
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.get(Unknown Source)
        at com.mucommander.ui.tabs.TabsCollection.get(TabsCollection.java:121)
        at com.mucommander.ui.tabs.TabsCollection.updateTab(TabsCollection.java:93)
        at com.mucommander.ui.tabs.HideableTabbedPane.updateCurrentTab(HideableTabbedPane.java:191)
        at com.mucommander.ui.main.tabs.FileTableTabs.updateTabLocation(FileTableTabs.java:84)
        at com.mucommander.ui.main.tabs.FileTableTabs.locationChanged(FileTableTabs.java:187)
        at com.mucommander.ui.event.LocationManager.lambda$fireLocationChanged$0(LocationManager.java:168)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at com.mucommander.ui.event.LocationManager.fireLocationChanged(LocationManager.java:168)
        at com.mucommander.ui.event.LocationManager.setCurrentFolder(LocationManager.java:118)
        at com.mucommander.ui.event.LocationManager.setCurrentFolder(LocationManager.java:80)
        at com.mucommander.core.LocationChanger.lambda$tryChangeCurrentFolderInternal$0(LocationChanger.java:85)
        at com.mucommander.core.LocationChanger.tryChangeCurrentFolderInternal(LocationChanger.java:99)
        at com.mucommander.ui.main.FolderPanel.tryChangeCurrentFolderInternal(FolderPanel.java:348)
        at com.mucommander.ui.main.tabs.FileTableTabs.show(FileTableTabs.java:71)
        at com.mucommander.ui.main.tabs.FileTableTabs.selectTab(FileTableTabs.java:66)
        at com.mucommander.ui.main.FolderPanel.<init>(FolderPanel.java:196)
        at com.mucommander.ui.main.MainFrame.lambda$new$3(MainFrame.java:313)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ... 1 more
```

**Comment by ahadas** [comment]
Thanks for reporting thus @demetriuzz, the stacktrace was very helpful

**Comment by ahadas** [comment]
Version 1.4.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.1-1)
