### ISSUE TITLE
mucommander does not work on java 10 on macOS

### ISSUE THREAD

**Issue by mrserb** [mucommander/mucommander#147]
It fails because of absent of Windows Look and Feel.
java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsLookAndFeel
 at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:848)
 at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:633)
 at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:598)
 at com.jidesoft.swing.StyledLabel.updateUI(StyledLabel.java:103)
 at java.desktop/javax.swing.JLabel.<init>(Unknown Source)
 at java.desktop/javax.swing.JLabel.<init>(Unknown Source)
 at com.jidesoft.swing.StyledLabel.<init>(StyledLabel.java:66)
 at com.jidesoft.swing.StyledLabelBuilder.createStyledLabel(StyledLabelBuilder.java:252)
 at com.mucommander.ui.main.table.FileTable$2.createRefreshNonExistingLocationLabel(FileTable.java:256)
 at com.mucommander.ui.main.table.FileTable$2.<init>(FileTable.java:252)
 at com.mucommander.ui.main.table.FileTable.createOverlayableTable(FileTable.java:248)
 at com.mucommander.ui.main.table.FileTable.<init>(FileTable.java:238)
 at com.mucommander.ui.main.FolderPanel.<init>(FolderPanel.java:169)
 at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:286)
 at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:272)
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.build(DefaultMainFramesBuilder.java:65)
 at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:166)
 at com.mucommander.muCommander.main(muCommander.java:582)
Caused by: java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
 at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
 at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
 at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
 ... 18 more

**Comment by Alefas** [comment]
I took jar file from app and was able to run it as "java -jar ...". Everything is fine, just Java icon instead of mucommander, however issue looks quite critical, would be nice to see it solved.

**Comment by ahadas** [comment]
Closing, was fixed by [this](https://github.com/mucommander/mucommander/commit/7391ccb0a3d2149c92760fb53e51627c8235836e). Thanks for reporting!
