### ISSUE TITLE
An error prevented muCommander from starting (MacOS)

### ISSUE THREAD

**Issue by ddj3o3** [mucommander/mucommander#165]
From 4 days the program doesn't work...

Capture of error:

java.lang.ExceptionInInitializerError
 at com.mucommander.ui.event.LocationManager.<init>(LocationManager.java:63)
 at com.mucommander.ui.main.FolderPanel.<init>(FolderPanel.java:89)
 at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:286)
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.createMainFrame(DefaultMainFramesBuilder.java:112)
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.build(DefaultMainFramesBuilder.java:83)
 at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:166)
 at com.mucommander.muCommander.run(muCommander.java:512)
 at com.mucommander.muCommander.main(muCommander.java:275)
Caused by: java.lang.NullPointerException
 at com.mucommander.commons.file.FileURL.getFileURL(FileURL.java:215)
 at com.mucommander.core.GlobalLocationHistory.<init>(GlobalLocationHistory.java:72)
 at com.mucommander.core.GlobalLocationHistory.<clinit>(GlobalLocationHistory.java:53)
 ... 8 more

Any  solutions?

Thx

**Comment by ahadas** [comment]
That means that one of the recent locations you visited cannot be "restored".
The simplest solution would be to remove the `recent_locations` section of the snapshot.xml file.
The location of snapshot.xml depends on the operating system you're using (`~/Library/Preferences/muCommander/` on Mac OS or `~/.mucommander` on all others).
It would be appreciated if you could share that `recent_locations` section so I could try figuring out which location is problematic.

**Comment by ddj3o3** [comment]
Thx for the reply but I didn't found the location of snapshot.xml (into preferences and/or mucommander).
Also I tried to install mucommander into other Mac ... same problem.

**Comment by ahadas** [comment]
Can you please provide the whole output before that exception? it should indicate where the configuration files are read from.

**Comment by GJRobert** [comment]
Have similar issue with muCommander 0.9.7 on Big Sur 11.4 (MacBook Air M1 2020), error message:
```java
java.lang.NullPointerException
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.build(DefaultMainFramesBuilder.java:64)
 at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:178)
 at com.mucommander.Application.run(Application.java:411)
 at com.mucommander.Application.run(Application.java:495)
 at com.mucommander.Activator.start(Activator.java:108)
 at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
 at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
 at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
 at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
 at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
 at java.lang.Thread.run(Thread.java:748)
```

I did not check if the messages are the same of the OP @ddj3o3 , but as I followed instruction by @ahadas to delete the `recent_locations` section in `~/Library/Preferences/muCommander/snapshot.xml`, muCommander 0.9.7 becomes normal to start. I feel lucky because I might be encountering not exactly same issue.

Here is my snapshot.xml:
```xml
...
    <recent_locations>
        <count>0</count>
    </recent_locations>
...
```
