### ISSUE TITLE
JNLPException Web Client

### ISSUE THREAD

**Issue by wheelq** [mucommander/mucommander#190]
JNLPException[category: Security Error : Exception: null : LaunchDesc: 
<jnlp spec="1.0+" version="0.9.3" codebase="http://www.mucommander.com/webstart/" href="mucommander.jnlp">
  <information>
    <title>muCommander</title>
    <vendor>Maxence Bernard</vendor>
    <homepage href="http://www.mucommander.com"/>
    <description>A cross-platform file manager.</description>
    <description kind="short">A cross-platform file manager.</description>
    <icon href="icon.gif"/>
    <offline-allowed/>
  </information>
  <security>
    <all-permissions/>
  </security>
  <resources os="Mac OS X">
    <property name="com.apple.smallTabs" value="true"/>
    <property name="com.apple.hwaccel" value="true"/>
    <property name="apple.laf.useScreenMenuBar" value="true"/>
    <property name="file.encoding" value="UTF-8"/>
  </resources>
  <resources>
    <j2se version="1.5+"/>
    <jar href="mucommander.jar"/>
  </resources>
  <application-desc main-class="com.mucommander.muCommander"/>
</jnlp> ]
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResourcesHelper(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
