### ISSUE TITLE
0.9.4 doesn't work on RPi4 RaspbianOS.

### ISSUE THREAD

**Issue by lee-yunseok** [mucommander/mucommander#284]
```
No config.properties found.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/usr/share/mucommander/mucommander-0.9.4.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR: Error creating bundle cache.
java.lang.Exception: Unable to create bundle cache lock file: java.io.FileNotFoundException: /usr/share/mucommander/felix-cache/cache.lock (Permission denied)
	at org.apache.felix.framework.cache.BundleCache.<init>(BundleCache.java:172)
	at org.apache.felix.framework.Felix.init(Felix.java:703)
	at org.apache.felix.framework.Felix.init(Felix.java:641)
	at com.mucommander.main.muCommander.main(muCommander.java:316)
Could not create framework: org.osgi.framework.BundleException: Error creating bundle cache.
org.osgi.framework.BundleException: Error creating bundle cache.
	at org.apache.felix.framework.Felix.init(Felix.java:708)
	at org.apache.felix.framework.Felix.init(Felix.java:641)
	at com.mucommander.main.muCommander.main(muCommander.java:316)
Caused by: java.lang.Exception: Unable to create bundle cache lock file: java.io.FileNotFoundException: /usr/share/mucommander/felix-cache/cache.lock (Permission denied)
	at org.apache.felix.framework.cache.BundleCache.<init>(BundleCache.java:172)
	at org.apache.felix.framework.Felix.init(Felix.java:703)
	... 2 more
```

After update 0.9.4 muCommander doesn't work. When I runs with `sudo` command, muCommander runs with the following log:

```
No config.properties found.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/usr/share/mucommander/mucommander-0.9.4.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
01:28:20.309 [FelixStartLevel] INFO com.mucommander.commons.runtime.OsFamily - Current OS family: Linux
01:28:20.353 [FelixStartLevel] INFO com.mucommander.commons.runtime.JavaVersion - Current Java version: 11
01:28:20.354 [FelixStartLevel] INFO com.mucommander.commons.runtime.JavaVersion - Current JVM architecture: arm
01:28:20.568 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.ar.Activator$1@1d8def6
01:28:20.591 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.bzip2.Activator$1@acd0c1
01:28:20.620 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.gzip.Activator$1@193c211
01:28:20.656 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.iso.Activator$1@6aa960
01:28:20.685 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.libguestfs.Activator$1@1700568
01:28:20.711 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.lst.Activator$1@f4cb52
01:28:20.742 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.rar.Activator$1@f73746
01:28:20.771 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.sevenzip.Activator$1@1173ee4
01:28:20.781 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.tar.Activator$1@1cb405
01:28:20.789 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.zip.Activator$1@155234f
01:28:20.795 [FelixStartLevel] DEBUG com.mucommander.conf.Activator - starting
01:28:21.147 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.ftp.Activator$1@1e7fc86
01:28:21.540 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.http.Activator$1@857bda
01:28:21.541 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.http.Activator$2@1d15c5e
01:28:21.582 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.nfs.Activator$1@14e390
01:28:21.663 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.ovirt.Activator$1@3327b3
01:28:21.730 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.registry.Activator$1@7d0ce6
01:28:21.731 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.registry.Activator$2@15c60dc
01:28:21.732 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.registry.Activator$3@98ac8c
01:28:21.734 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.registry.Activator$4@c081b9
01:28:21.899 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.s3.Activator$1@11e789f
01:28:21.928 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.sftp.Activator$1@14f3f4f
01:28:21.968 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.smb.Activator$1@57fdd5
01:28:22.005 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.vsphere.Activator$1@17c2639
01:28:22.029 [FelixStartLevel] INFO com.mucommander.text.Activator - Using language set in preferences: en
01:28:22.030 [FelixStartLevel] INFO com.mucommander.text.Activator - Found exact match (language+country) for locale en
01:28:22.032 [FelixStartLevel] DEBUG com.mucommander.text.Activator - Current language has been set to en
   ____  _____ _______             _____    ________    ____
  / __ \/ ___// ____(_)___ _____ _/ ___/   / ____/ /   /  _/
 / / / /\__ \/ / __/ / __ `/ __ `/\__ \   / /   / /    / /  
/ /_/ /___/ / /_/ / / /_/ / /_/ /___/ /  / /___/ /____/ /   
\____//____/\____/_/\__,_/\__,_//____/   \____/_____/___/   

:: https://github.com/renatoathaydes/osgiaas ::

[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:235)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:227)
	at com.athaydes.osgiaas.cli.core.CliRun.<init>(CliRun.java:45)
	at com.athaydes.osgiaas.cli.core.StandardCli.start(StandardCli.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.felix.scr.impl.inject.BaseMethod.invokeMethod(BaseMethod.java:229)
	at org.apache.felix.scr.impl.inject.BaseMethod.access$500(BaseMethod.java:39)
	at org.apache.felix.scr.impl.inject.BaseMethod$Resolved.invoke(BaseMethod.java:650)
	at org.apache.felix.scr.impl.inject.BaseMethod.invoke(BaseMethod.java:506)
	at org.apache.felix.scr.impl.inject.ActivateMethod.invoke(ActivateMethod.java:307)
	at org.apache.felix.scr.impl.inject.ActivateMethod.invoke(ActivateMethod.java:299)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:298)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:109)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:906)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:879)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:749)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:675)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:430)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:657)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:341)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:390)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:54)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:265)
	at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:254)
	at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:227)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:420)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4817)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2336)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:834)

>> 01:28:23.745 [FelixStartLevel] DEBUG com.mucommander.Activator - starting
01:28:23.778 [FelixStartLevel] INFO com.mucommander.ui.main.osgi.ProtocolPanelProviderTracker - ProtocolPanelProvider is registered: com.mucommander.commons.file.protocol.nfs.Activator$2@1c5cc77
01:28:23.778 [FelixStartLevel] INFO com.mucommander.ui.main.osgi.ProtocolPanelProviderTracker - ProtocolPanelProvider is registered: com.mucommander.commons.file.protocol.s3.Activator$2@13e9f8d
01:28:23.778 [FelixStartLevel] INFO com.mucommander.ui.main.osgi.ProtocolPanelProviderTracker - ProtocolPanelProvider is registered: com.mucommander.commons.file.protocol.sftp.Activator$2@5f2487
01:28:23.779 [FelixStartLevel] INFO com.mucommander.ui.main.osgi.ProtocolPanelProviderTracker - ProtocolPanelProvider is registered: com.mucommander.commons.file.protocol.http.Activator$3@d9d480
01:28:23.779 [FelixStartLevel] INFO com.mucommander.ui.main.osgi.ProtocolPanelProviderTracker - ProtocolPanelProvider is registered: com.mucommander.commons.file.protocol.vsphere.Activator$2@1720b98
01:28:23.779 [FelixStartLevel] INFO com.mucommander.ui.main.osgi.ProtocolPanelProviderTracker - ProtocolPanelProvider is registered: com.mucommander.commons.file.protocol.registry.Activator$5@c7324c
01:28:23.779 [FelixStartLevel] INFO com.mucommander.ui.main.osgi.ProtocolPanelProviderTracker - ProtocolPanelProvider is registered: com.mucommander.commons.file.protocol.ftp.Activator$2@11f578f
01:28:23.779 [FelixStartLevel] INFO com.mucommander.ui.main.osgi.ProtocolPanelProviderTracker - ProtocolPanelProvider is registered: com.mucommander.commons.file.protocol.ovirt.Activator$2@1c4e8f8
01:28:23.780 [FelixStartLevel] INFO com.mucommander.ui.main.osgi.ProtocolPanelProviderTracker - ProtocolPanelProvider is registered: com.mucommander.commons.file.protocol.smb.Activator$2@1f0f53
01:28:23.784 [FelixStartLevel] INFO com.mucommander.text.TranslationTracker - TranslationService is registered: com.mucommander.text.Activator$1@87ab19
01:28:23.791 [FelixStartLevel] INFO com.mucommander.osgi.FileViewerServiceTracker - FileViewerService is registered: com.mucommander.viewer.image.ImageFileViewerService@1fbe68f
01:28:23.791 [FelixStartLevel] INFO com.mucommander.osgi.FileViewerServiceTracker - FileViewerService is registered: com.mucommander.viewer.binary.BinaryFileViewerService@1c9b2e4
01:28:23.792 [FelixStartLevel] INFO com.mucommander.osgi.FileViewerServiceTracker - FileViewerService is registered: com.mucommander.viewer.text.TextFileViewerService@84e425
01:28:23.795 [FelixStartLevel] INFO com.mucommander.osgi.FileEditorServiceTracker - FileEditorService is registered: com.mucommander.viewer.text.TextFileViewerService@84e425
Could not load custom commands: /root/.mucommander/commands.xml (No such file or directory). Using default values.
Could not load custom associations: /root/.mucommander/associations.xml (No such file or directory). Using default values.
Could not load bookmarks: /root/.mucommander/bookmarks.xml (No such file or directory). Using default values.
```

0.9.4 always need `sudo` so I downgraded to 0.9.3.

**Comment by ahadas** [comment]
@lee-yunseok  thanks for reporting this.
Actually, version 0.9.4 doesn't require sudo but it needs to be able to create the felix-cache directory under the installation folder (if it doesn't exist) and write there. Generally, this directory is created during the installation process (e.g., with rpm/deb) but apparently you install it in a different way. I would suggest to create the directory `/usr/share/mucommander/felix-cache/` manually (with write permissions for your user) and start the application without sudo.
Did you just extract the tar.gz file?

**Comment by ahadas** [comment]
@lee-yunseok updated the tgz and portable files

**Comment by lee-yunseok** [comment]
@ahadas Thank you for your work!

**Comment by ahadas** [comment]
@lee-yunseok ack, I thought you're sing the tgz file. ok, so this will likely be solved by the fix for #287

**Comment by lee-yunseok** [comment]
@ahadas Yes I saw #287, thank you for your work.

**Comment by ahadas** [comment]
Version 0.9.4-2 with the fix has been released

**Comment by lee-yunseok** [comment]
@ahadas It works perfect. Thanks!

**Comment by ahadas** [comment]
@lee-yunseok happy to hear :) thanks for the update
