### ISSUE TITLE
mucommander (0.9.4-1) run error

### ISSUE THREAD

**Issue by demetriuzz** [mucommander/mucommander#287]
Work on Linux Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)
Version 0.9.3 work is good!

Update mucommander to 0.9.4-1.
Run mucommander from not root!

```
$ mucommander 
No config.properties found.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/usr/share/mucommander/mucommander-0.9.4.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR: Error creating bundle cache.
java.lang.Exception: Unable to create bundle cache lock file: java.io.FileNotFoundException: /usr/share/mucommander/felix-cache/cache.lock (Отказано в доступе)
	at org.apache.felix.framework.cache.BundleCache.<init>(BundleCache.java:172)
	at org.apache.felix.framework.Felix.init(Felix.java:703)
	at org.apache.felix.framework.Felix.init(Felix.java:641)
	at com.mucommander.main.muCommander.main(muCommander.java:316)
Could not create framework: org.osgi.framework.BundleException: Error creating bundle cache.
org.osgi.framework.BundleException: Error creating bundle cache.
	at org.apache.felix.framework.Felix.init(Felix.java:708)
	at org.apache.felix.framework.Felix.init(Felix.java:641)
	at com.mucommander.main.muCommander.main(muCommander.java:316)
Caused by: java.lang.Exception: Unable to create bundle cache lock file: java.io.FileNotFoundException: /usr/share/mucommander/felix-cache/cache.lock (Отказано в доступе)
	at org.apache.felix.framework.cache.BundleCache.<init>(BundleCache.java:172)
	at org.apache.felix.framework.Felix.init(Felix.java:703)
	... 2 more
```

**Comment by ahadas** [comment]
@demetriuzz thanks for reporting this. How did you install the application? by extracting the tgz file or using the deb file?

**Comment by demetriuzz** [comment]
Good day!
I do:
`sudo dpkg -i mucommander_0.9.4-1_all.deb`

Version 0.9.3 was also installed via dpkg.

**Comment by ahadas** [comment]
Version 0.9.4-2 with the fix has been released
