### ISSUE TITLE
access to SMB as guest

### ISSUE THREAD

**Issue by gnjmn** [mucommander/mucommander#293]
Hello 
i'm trying to connect to a SMB as guest but cant make it happen,
it worked perfectly when i was on W7 but since W10 can't make it work...
Don't know if the issue is about mucommander or Windows settings,
please someone help me

**Comment by ahadas** [comment]
@gnjmn hi, Microsoft has disabled SMB v1, which is the only version muCommander supports at the moment, in Windows 10.
You can enable it by following the following guide (but check SMB server rather than client):
https://www.tachytelic.net/2019/09/windows-10-enable-smb1/
Note that Microsoft disabled it by default due to security vulnerability in SMB v1.

**Comment by gnjmn** [comment]
yes i've heard of that and did activate smb1 but give me an error windows when trying to connect that says "Failed to connect: 0.0.0.0<00>/X.X.X.X

**Comment by ahadas** [comment]
Ah ok. I had an issue to connect as a user with no "local password" (maybe it was called differently) - so I configured one. This password is unrelated to an account - can be set in the user settings.

**Comment by gnjmn** [comment]
the entire error code is:
jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/(IP address of SMB server)
jcifs.util.transport.TransportException: Connection timeout
 at jcifs.util.transport.Transport.connect(Transport.java:174)
 at jcifs.smb.SmbTransport.connect(SmbTransport.java:297)
 at jcifs.smb.SmbTree.treeConnect(SmbTree.java:156)
 at jcifs.smb.SmbFile.doConnect(SmbFile.java:906)
 at jcifs.smb.SmbFile.doShareEnum(SmbFile.java:1781)
 at jcifs.smb.SmbFile.doEnum(SmbFile.java:1729)
 at jcifs.smb.SmbFile.listFiles(SmbFile.java:1708)
 at jcifs.smb.SmbFile.listFiles(SmbFile.java:1686)
 at com.mucommander.commons.file.impl.smb.SMBFile.ls(SMBFile.java:470)
 at com.mucommander.commons.file.impl.smb.SMBFile.ls(SMBFile.java:379)
 at com.mucommander.commons.file.AbstractFile.ls(AbstractFile.java:517)
 at com.mucommander.ui.main.FolderPanel$ChangeFolderThread.run(FolderPanel.java:1105)

 at jcifs.smb.SmbTransport.connect(SmbTransport.java:299)
 at jcifs.smb.SmbTree.treeConnect(SmbTree.java:156)
 at jcifs.smb.SmbFile.doConnect(SmbFile.java:906)
 at jcifs.smb.SmbFile.doShareEnum(SmbFile.java:1781)
 at jcifs.smb.SmbFile.doEnum(SmbFile.java:1729)
 at jcifs.smb.SmbFile.listFiles(SmbFile.java:1708)
 at jcifs.smb.SmbFile.listFiles(SmbFile.java:1686)
 at com.mucommander.commons.file.impl.smb.SMBFile.ls(SMBFile.java:470)
 at com.mucommander.commons.file.impl.smb.SMBFile.ls(SMBFile.java:379)
 at com.mucommander.commons.file.AbstractFile.ls(AbstractFile.java:517)
 at com.mucommander.ui.main.FolderPanel$ChangeFolderThread.run(FolderPanel.java:1105)

**Comment by ahadas** [comment]
I see, this probably means that SMB v1 is still not properly exposed.
I've just recorded a video that demonstrates how to configure that:
https://youtu.be/4Ebwvabn6Cs

**Comment by ahadas** [comment]
Closing, please feel free to reopen if it's still relevant.
