### ISSUE TITLE
An error prevented muCommander from starting.

### ISSUE THREAD

**Issue by 379820** [mucommander/mucommander#294]
At very first time crashes on startup with runtime exception,

Version information

muCommander
Version: 0.9.4
Build date: 2020/03/08
Build number: 8f24dfc

Java
Runtime version: 11.0.4
VM name: OpenJDK 64-Bit Server VM
VM version: 11.0.4+11
VM vendor: AdoptOpenJDK

OS
Name: Mac OS X
Version: 10.15.3
Architecture: x86_64

Locale
Language: en
Country: RU
Encoding: UTF-8

But next run all is fine
```
java.lang.RuntimeException
 at com.mucommander.ui.event.LocationManager.setCurrentFolder(LocationManager.java:83)
 at com.mucommander.core.LocationChanger$1.run(LocationChanger.java:105)
 at com.mucommander.core.LocationChanger.tryChangeCurrentFolderInternal(LocationChanger.java:119)
 at com.mucommander.ui.main.FolderPanel.tryChangeCurrentFolderInternal(FolderPanel.java:347)
 at com.mucommander.ui.main.tabs.FileTableTabs.show(FileTableTabs.java:72)
 at com.mucommander.ui.main.tabs.FileTableTabs.selectTab(FileTableTabs.java:67)
 at com.mucommander.ui.main.FolderPanel.<init>(FolderPanel.java:176)
 at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:285)
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.createMainFrame(DefaultMainFramesBuilder.java:119)
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.build(DefaultMainFramesBuilder.java:67)
 at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:166)
 at com.mucommander.Application.run(Application.java:435)
 at com.mucommander.Application.run(Application.java:522)
 at com.mucommander.Activator.start(Activator.java:70)
 at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
 at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
 at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
 at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
 at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
 at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by ahadas** [comment]
@379820  thanks for reporting this. I noticed that as well. It happens when a location that was previously browsed in an active tab is not accessible when the application tries to restore it during startup (that's the default behavior, to restore the previously browsed locations). It's bothering indeed.

**Comment by ahadas** [comment]
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)
