### ISSUE TITLE
Failed to start in Fedora 34

### ISSUE THREAD

**Issue by wffger** [mucommander/mucommander#458]
I install mucommander-0.9.6-1.noarch.rpm in Fedora 34. But program failed to start.

Openjdk is installed：
```
[ydx@fedora rime]$ java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode, sharing)
```

Error:
```
[ydx@fedora rime]$ mucommander 
No config.properties found.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/usr/share/mucommander/mucommander-0.9.6.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR: Bundle Jakarta Commons Logging [8] Error starting file:/usr/share/mucommander/bundle/commons-logging-1.1.1.jar (org.osgi.framework.BundleException: Unable to resolve Jakarta Commons Logging [8](R 8.0): missing requirement [Jakarta Commons Logging [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=org.apache.avalon.framework.logger) Unresolved requirements: [[Jakarta Commons Logging [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=org.apache.avalon.framework.logger)])
org.osgi.framework.BundleException: Unable to resolve Jakarta Commons Logging [8](R 8.0): missing requirement [Jakarta Commons Logging [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=org.apache.avalon.framework.logger) Unresolved requirements: [[Jakarta Commons Logging [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=org.apache.avalon.framework.logger)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:829)
01:33:39.506 [FelixStartLevel] INFO com.mucommander.commons.runtime.OsFamily - Current OS family: Linux
01:33:39.512 [FelixStartLevel] INFO com.mucommander.commons.runtime.JavaVersion - Current Java version: 11
01:33:39.512 [FelixStartLevel] INFO com.mucommander.commons.runtime.JavaVersion - Current JVM architecture: amd64
01:33:39.523 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.ar.Activator$1@143388d5
01:33:39.529 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.bzip2.Activator$1@7b06c6fe
01:33:39.536 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.gzip.Activator$1@49529bd8
01:33:39.540 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.iso.Activator$1@5b5ec853
01:33:39.544 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.libguestfs.Activator$1@7c10d723
01:33:39.548 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.lst.Activator$1@312f08b7
01:33:39.552 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.rar.Activator$1@5be12d3c
01:33:39.557 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.sevenzip.Activator$1@56edffd3
01:33:39.559 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.tar.Activator$1@2d03c346
01:33:39.560 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileFormatServiceTracker - FileFormatService is registered: com.mucommander.commons.file.archive.zip.Activator$1@36c6f7a3
01:33:39.573 [FelixStartLevel] DEBUG com.mucommander.conf.Activator - starting
01:33:39.586 [FelixStartLevel] ERROR com.mucommander.conf.MuConfigurations - failed to load preferences
java.io.FileNotFoundException: /home/ydx/.mucommander/preferences.xml (没有那个文件或目录)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.mucommander.commons.file.protocol.local.LocalFile.getInputStream(LocalFile.java:602)
	at com.mucommander.io.backup.BackupInputStream.getInputStream(BackupInputStream.java:84)
	at com.mucommander.io.backup.BackupInputStream.<init>(BackupInputStream.java:60)
	at com.mucommander.conf.MuConfigurationFile.getReader(MuConfigurationFile.java:122)
	at com.mucommander.commons.conf.Configuration.read(Configuration.java:349)
	at com.mucommander.conf.MuPreferences.read(MuPreferences.java:396)
	at com.mucommander.conf.MuConfigurations.loadPreferences(MuConfigurations.java:59)
	at com.mucommander.conf.Activator.start(Activator.java:14)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:829)
01:33:39.595 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.ftp.Activator$1@437677d7
01:33:39.600 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.gdrive.Activator$1@af7204e
01:33:39.653 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.http.Activator$1@65aa6ad5
01:33:39.653 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.http.Activator$2@6249fdc4
01:33:39.657 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.nfs.Activator$1@4cd5ae53
01:33:39.673 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.ovirt.Activator$1@2b6f8e15
01:33:39.678 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.registry.Activator$1@530964c6
01:33:39.678 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.registry.Activator$2@5311ab92
01:33:39.679 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.registry.Activator$3@614ac8ce
01:33:39.679 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.registry.Activator$4@17e5c457
01:33:39.696 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.s3.Activator$1@54610816
01:33:39.701 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.sftp.Activator$1@63b57831
01:33:39.705 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.smb.Activator$1@43ee6e3a
01:33:39.708 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.commons.file.protocol.vsphere.Activator$1@6b5f4ee0
01:33:39.713 [FelixStartLevel] INFO com.mucommander.text.Activator - Language not set in preferences, trying to match system's language (zh_CN)
01:33:39.713 [FelixStartLevel] INFO com.mucommander.text.Activator - Found exact match (language+country) for locale zh_CN
01:33:39.713 [FelixStartLevel] DEBUG com.mucommander.text.Activator - Current language has been set to zh-CN
ERROR: Bundle mucommander-viewer-text [94] Error starting file:/usr/share/mucommander/bundle/mucommander-viewer-text-0.9.6.jar (org.osgi.framework.BundleException: Activator start error in bundle mucommander-viewer-text [94].)
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.fc34.x86_64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1399)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1397)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1396)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1429)
	at com.mucommander.snapshot.MuSnapshot.<init>(MuSnapshot.java:550)
	at com.mucommander.snapshot.MuSnapshot.<clinit>(MuSnapshot.java:59)
	at com.mucommander.viewer.text.Activator.start(Activator.java:39)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:829)
01:33:39.796 [FelixStartLevel] DEBUG com.mucommander.Activator - starting
01:33:39.798 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.Activator$2@3429df0d
01:33:39.799 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is registered: com.mucommander.Activator$3@28c2679f
01:33:39.808 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is unregistered: com.mucommander.Activator$2@3429df0d
01:33:39.808 [FelixStartLevel] INFO com.mucommander.commons.file.osgi.FileProtocolServiceTracker - FileProtocolService is unregistered: com.mucommander.Activator$3@28c2679f
ERROR: Bundle mucommander-core [105] Error starting file:/usr/share/mucommander/app/mucommander-core-0.9.6.jar (org.osgi.framework.BundleException: Activator start error in bundle mucommander-core [105].)
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.desktop/java.awt.Component.<clinit>(Component.java:621)
	at com.mucommander.ui.main.osgi.ProtocolPanelProviderTracker.addingService(ProtocolPanelProviderTracker.java:24)
	at com.mucommander.ui.main.osgi.ProtocolPanelProviderTracker.addingService(ProtocolPanelProviderTracker.java:13)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264)
	at com.mucommander.Activator.start(Activator.java:90)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by wffger** [comment]
I install openjdk and it works now.

```
dnf provides /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.fc34.x86_64/lib/libawt_xawt.so
sudo dnf install java-11-openjdk-1:11.0.11.0.9-0.fc34.x86_64
```
I don't know why I can get java version message before I install it.

**Comment by ahadas** [comment]
> I don't know why I can get java version message before I install it.

Yeah, maybe by default Fedora 34 comes with headless Java now and therefore `java.awt.Toolkit` was missing

**Comment by ahadas** [comment]
we used to have a check for that, but maybe with the transition of OSGi it's no effective anymore - I'll need to check it

**Comment by ahadas** [comment]
Alright, so my initial suspicion was right - Fedora 34 comes by default with `java-11-openjdk-headless`. The check `GraphicsEnvironment.isHeadless()` returns `false` though and thus the application starts and later fails when it tries to load things from the `java.awt` package.
