### ISSUE TITLE
0.9.7-1: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Object java.util.AbstractMap.clone()

### ISSUE THREAD

**Issue by gnh1201** [mucommander/mucommander#465]
Environment: Windows 10

```
C:\Program Files (x86)\muCommander>java -jar mucommander-0.9.7.jar
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Object java.util.AbstractMap.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.util" to unnamed module @2d38eb89
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.beust.jcommander.Parameterized.parseArg(Parameterized.java:123)
        at com.beust.jcommander.JCommander.addDescription(JCommander.java:601)
        at com.beust.jcommander.JCommander.createDescriptions(JCommander.java:594)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:249)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:235)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:227)
        at com.mucommander.main.muCommander.main(muCommander.java:213)
```

**Comment by ahadas** [comment]
Could be related to [this report](https://youtrack.jetbrains.com/issue/SCL-18806)
@gnh1201 What version of Java do you use? do you use Scala plugin?

**Comment by gnh1201** [comment]
I checked two versions of JDK 16 (Oracle and OpenJDK). All get the same error.

**Comment by ahadas** [comment]
I see, Java 16, thanks. I didn't test with Java 16 so there may well be an issue with that. Note that you can download the [bundled version](https://github.com/mucommander/mucommander/releases/download/0.9.7-1/mucommander-0.9.7-1-bundled.exe) that includes the JRE inside if you want to run muCommander without installing another version of Java.

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
