### ISSUE TITLE
IllegalAccessError on macOS

### ISSUE THREAD

**Issue by twwwt** [mucommander/mucommander#47]
I have downloaded the latest release 0.9.1 and tried to start it on macOS with Java 8 installed locally. I get the following exception:

```
java.lang.IllegalAccessError: class com.jidesoft.plaf.LookAndFeelFactory (in unnamed module @0x40cb8df7) cannot access class com.sun.java.swing.plaf.windows.WindowsLookAndFeel (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @0x40cb8df7
 at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:848)
 at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:633)
 at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:598)
 at com.jidesoft.swing.StyledLabel.updateUI(StyledLabel.java:103)
 at javax.swing.JLabel.<init>(java.desktop@9-ea/JLabel.java:162)
 at javax.swing.JLabel.<init>(java.desktop@9-ea/JLabel.java:233)
 at com.jidesoft.swing.StyledLabel.<init>(StyledLabel.java:66)
 at com.jidesoft.swing.StyledLabelBuilder.createStyledLabel(StyledLabelBuilder.java:252)
 at com.mucommander.ui.main.table.FileTable$2.createRefreshNonExistingLocationLabel(FileTable.java:256)
 at com.mucommander.ui.main.table.FileTable$2.<init>(FileTable.java:252)
 at com.mucommander.ui.main.table.FileTable.createOverlayableTable(FileTable.java:248)
 at com.mucommander.ui.main.table.FileTable.<init>(FileTable.java:238)
 at com.mucommander.ui.main.FolderPanel.<init>(FolderPanel.java:169)
 at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:286)
 at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:272)
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.build(DefaultMainFramesBuilder.java:65)
 at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:166)
 at com.mucommander.muCommander.main(muCommander.java:582)
```

**Comment by ahadas** [comment]
I see reports on this issues related to Java 9..
What is the exact version of Java 8 you're using and how did you install it?

**Comment by twwwt** [comment]
I'm using java version "1.8.0_111". When I installed it I had version 0.9.0 installed: I dragged the new version into the applications folder thereby replacing the former version. After that MuCommander didn't start at all. So I trashed it, downloaded it again, and dragged it again from the image into the applications folder. After that I got the exception. Could it be that some file(s) are left overs (somewhere in the home directory) that may cause the exception?

**Comment by jkost** [comment]
I 'm using 1.8.0_112, but when I started Java Control Panel it pointed to the uninstalled JDK 9 EA. I had to manually remove /Library/PreferencePanes/JavaControlPanel.prefPane and /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin and reinstall JDK 8u112 to resolve the problem.

**Comment by ahadas** [comment]
@jkost thanks for the reported resolution.
@twwwt - did this solution work for you?
I guess that:
Short term - this needs to updated in the documentation
Long term - it might have been a mistake to use JIDE components. There is very limited use of them though, so need to consider to replace them in the next release.

**Comment by twwwt** [comment]
@ahadas @jkost Indeed, I had the exact same problem (leftovers from a previous JDK9 installation). After following the steps, it works now. Thanks!

**Comment by ahadas** [comment]
I removed the dependency on JIDE components so adding a note in the readme file may be redundant.
Closing it for now, if it would still happen I'll then update the 'known issues' in the readme file.

**Comment by essobedo** [comment]
@ahadas FYI I still face the exact same issue with the current master. To workaround the problem (since I don't want to remove Java 9 as suggested above) I simply configure macAppBundle to bundle the JRE into the app file by simply adding `bundleJRE = true` as next:

```
macAppBundle {
    appName = "muCommander"
    mainClassName = "com.mucommander.muCommander"
    appStyle = "Oracle"
    bundleIdentifier = "com.mucommander.muCommander"
    jvmVersion = "1.6+"
    bundleJRE = true
   ...
```
This way I directly have the JRE 8 in the app.

NB: To prevent having the JRE 9 in my app when we launch `./gradlew createDmg`, we first have to ensure that `/usr/libexec/java_home` returns the path to my Java 8, if it returns the path to my Java 9, we can rename `/Library/Java/JavaVirtualMachines/1.9.0.jdk/Contents/Info.plist` to `/Library/Java/JavaVirtualMachines/1.9.0.jdk/Contents/Info.plist.disabled` as described [here](https://gist.github.com/hogmoru/8e02cf826c840914a8ed93fd418ed88e).

It is up to you now, but maybe you could do the same and propose the app file with the right JRE by default to prevent getting this error since Java 9 is officially released now which means that people will face this issue more often.
