### ISSUE TITLE
mucommander doesn't start on Linux Mint 20.2 "Uma" - Cinnamon

### ISSUE THREAD

**Issue by dietmarwo** [mucommander/mucommander#498]
After upgrading my Linux Mint installation to 20.2 "Uma" https://linuxmint.com/edition.php?id=288 starting mucommander fails.
Tried all versions from 0.95 up to the current version on github. On Mint 20.1 all versions work. 

java --version     gives:

openjdk 11.0.10 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)

./gradlew run     results in:

2021-08-10 10:10:06.195 [FelixStartLevel] ERROR com.mucommander.Application:446 - Startup failed
java.lang.ExceptionInInitializerError: null
        at com.mucommander.ui.event.LocationManager.<init>(LocationManager.java:67)
        at com.mucommander.ui.main.FolderPanel.<init>(FolderPanel.java:87)
        at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:262)
        at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.createMainFrame(DefaultMainFramesBuilder.java:119)
        at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
        at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.build(DefaultMainFramesBuilder.java:67)
        at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:178)
        at com.mucommander.Application.run(Application.java:411)
        at com.mucommander.Application.run(Application.java:495)
        at com.mucommander.Activator.start(Activator.java:102)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
        at com.mucommander.commons.file.FileURL.getFileURL(FileURL.java:217)
        at com.mucommander.core.GlobalLocationHistory.<init>(GlobalLocationHistory.java:70)
        at com.mucommander.core.GlobalLocationHistory.<clinit>(GlobalLocationHistory.java:51)
        ... 23 common frames omitted

so it seems that getFileURL is called with null:

216    public static FileURL getFileURL(String location) throws MalformedURLException {
217        int schemeDelimPos = location.indexOf("://");

Tried a (simple) fix moving the try up to catch the NPE:

 ```
  public static FileURL getFileURL(String location) throws MalformedURLException {
       FileURL fileURL = null;
       try {
            int schemeDelimPos = location.indexOf("://");
            SchemeHandler handler;

            if(schemeDelimPos==-1) {
                // No scheme: the location is a local or UNC path, not a URL
                handler = getDefaultHandler();
            }
            else {
                handler = getSchemeHandler(location.substring(0, schemeDelimPos));
            }
            fileURL = new FileURL(handler);
            handler.getParser().parse(location, fileURL);
        }
        catch(Exception e) {
            // Catch any unexpected exception thrown by the SchemeParser and turn it into a MalformedURLException
            // with a specific error message.
            if(e instanceof MalformedURLException)
                throw (MalformedURLException)e;

            throw new MalformedURLException("URL parser error");
        }
        return fileURL;
    }

```
Which seems to work - got mucommander starting again.

**Comment by ahadas** [comment]
Thanks for reporting this.
That is interesting. It means that in snapshot.xml we had the history block but at least one of the items was missing.
I can't see how this can happen without ending up with a malformed xml, however, adding protection against that is fairly easy. I'll do it a bit differently though so it would be more clear what's the reason for that protection.

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
