### ISSUE TITLE
Cannot unpack multi-volume RAR archives

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#840]
I already reported this issue in #469, but #469 has been closed some time ago. However, the issue still exists.
muCommander cannot unpack multi-volume RAR archives, neither in RAR4 nor RAR5 format.

Please see example here (I had to zip them, because GitHub doesn't allow to upload RAR files):
[Test_RAR4.zip](https://github.com/mucommander/mucommander/files/10368250/Test_RAR4.zip)
[Test_RAR5.zip](https://github.com/mucommander/mucommander/files/10368251/Test_RAR5.zip)

The still existing inability to unpack multi-volume RAR archives is a bit surprising, because in #420 it is mentioned that 7-Zip-Binding has been added to muCommander, and 7-Zip _**is**_ able to unpack multi-volume RAR archives.

**Comment by pskowronek** [comment]
```
java.io.IOException: Wrong file signature was 526172211A070019 but should be 526172211A070100
        at com.mucommander.sevenzipjbindings.SignatureCheckedRandomAccessFile.openStreamAndCheckSignature(SignatureCheckedRandomAccessFile.java:217)
        at com.mucommander.sevenzipjbindings.SignatureCheckedRandomAccessFile.<init>(SignatureCheckedRandomAccessFile.java:58)
        at com.mucommander.sevenzipjbindings.SevenZipJBindingROArchiveFile.openInArchive(SevenZipJBindingROArchiveFile.java:81)
        at com.mucommander.sevenzipjbindings.SevenZipJBindingROArchiveFile.check(SevenZipJBindingROArchiveFile.java:75)
        at com.mucommander.commons.file.archive.rar.RarFormatProvider.getFile(RarFormatProvider.java:56)
        at com.mucommander.commons.file.FileFactory.wrapArchive(FileFactory.java:682)
        at com.mucommander.commons.file.FileFactory.getFile(FileFactory.java:491)
        at com.mucommander.commons.file.FileFactory.getFile(FileFactory.java:416)
        at com.mucommander.commons.file.protocol.local.LocalFile.ls(LocalFile.java:829)
        at com.mucommander.commons.file.protocol.local.LocalFile.ls(LocalFile.java:668)
        at com.mucommander.commons.file.AbstractFile.ls(AbstractFile.java:543)
        at com.mucommander.ui.event.LocationManager.setCurrentFolder(LocationManager.java:88)
        at com.mucommander.core.LocationChanger.setCurrentFolder(LocationChanger.java:352)
        at com.mucommander.core.BrowseLocationThread.run(BrowseLocationThread.java:381)
```

**Comment by pskowronek** [comment]
https://github.com/borisbrodski/sevenzipjbinding/issues/41 - probably relevant

**Comment by ahadas** [comment]
@pskowronek note that the wrong file signature error is expected for RAR < 5 - we try to open it with sevenzip and fall back to junrar in case of a failure

**Comment by pskowronek** [comment]
> @pskowronek note that the wrong file signature error is expected for RAR < 5 - we try to open it with sevenzip and fall back to junrar in case of a failure

oh, didn't know that

**Comment by ShayArtzi** [comment]
Hi folks,
I was looking into this issue, and found out that `sevenzipjbind` actually support multi-volume `rar` archives (see [docs](https://sevenzipjbind.sourceforge.net/extraction_snippets.html#open-multipart-rar-archives)). To achieve that one needs to implement the right callback interfaces (`IArchiveOpenVolumeCallback` and `IArchiveOpenCallback`).

I created a dirty fix locally and was able to extract the sample pdf attached in this discussion thread.

To create a full PR we will probably need to tweak `SignatureCheckedRandomAccessFile` and I need your help in choosing the right way to do it: one option is to have a special implementation for `rar` archive callback and avoid impacting the rest of file formats supported by 7z.

Thanks!

**Comment by ahadas** [comment]
hi @ShayArtzi , awesome but why limiting this to rar archive? isn't it similar to 7z archived?

**Comment by ShayArtzi** [comment]
@ahadas I'm realizing just now that multi volume 7z files are not supported as well... let me try to see if I can do both - I'll try to prepare a PR this week.

BTW - Multi part rar files have a `partY.rar` extension, while 7z multi part files have a `7x.YYY` extension, so currently mucommander doesn't event recognize the latter as valid archives.

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)
