### ISSUE TITLE
OSX -MacPro crash

### ISSUE THREAD

**Issue by buglyobalazs** [mucommander/mucommander#889]
Hi all,

I just want to install the 1.1.0 to my macbook pro, but it seems that i has some kind of error. i dont know what to do.
if a click the icon after the install. the small popup is appeare and after some sex this is come.

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at com.mucommander.ui.main.table.FileTableModel.getValueAt(FileTableModel.java:792)
at com.mucommander.ui.main.table.FileTable.doAutoLayout(FileTable.java:1100)
at com.mucommander.ui.main.table.FileTable.doLayout(FileTable.java:1148)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validateTree(Unknown Source)
at java.desktop/java.awt.Container.validate(Unknown Source)
at java.desktop/java.awt.Container.validateUnconditionally(Unknown Source)
at java.desktop/java.awt.Window.show(Unknown Source)
at java.desktop/java.awt.Component.show(Unknown Source)
at java.desktop/java.awt.Component.setVisible(Unknown Source)
at java.desktop/java.awt.Window.setVisible(Unknown Source)
at com.mucommander.ui.main.WindowManager.lambda$createNewMainFrame$1(WindowManager.java:202)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:202)
at com.mucommander.Application.run(Application.java:404)
at com.mucommander.Application.run(Application.java:488)
at com.mucommander.Activator.start(Activator.java:106)
at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
at org.apache.felix.framework.Felix.activateBundle(Felix.java:2429)
at org.apache.felix.framework.Felix.startBundle(Felix.java:2335)
at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
at java.base/java.lang.Thread.run(Unknown Source)

The same procedure was made on my iMac and that was good, i like it on my iMac.

macbook M1 2021 version.

is any had the same problem ?

**Comment by pskowronek** [comment]
What macOS version?

Are you trying to run muC installed via DMG downloaded from https://github.com/mucommander/mucommander/releases?

**Comment by buglyobalazs** [comment]
13.2.1 OSX.

Just downloaded the dmg from the web. [muCommander-1.1.0-1.dmg] not the Nightly from the GITHUB. 

Can the Java be problem? As i remember i have JRE and JDK too, on the pro.

**Comment by pskowronek** [comment]
Interesting. @ahadas, shouldn't muC use the embedded jre?

**Comment by ahadas** [comment]
yeah, the bundled JRE is should be used.
I think the problem disappeared because the snapshot.xml file disappeared, I'm not sure whether it's really related to the version of Java. @buglyobalazs if it happens again, please back up snapshot.xml that resides within [the folder that holds you customization files](https://github.com/mucommander/mucommander/wiki/Preference-Files) and share it - maybe it would shed more light on what's going on
