### ISSUE TITLE
moving dirs with rars : out of memory error

### ISSUE THREAD

**Issue by JamesOlvertone** [mucommander/mucommander#951]
OS: Linux
JRE: tested with Oracle Java 20 and 11.0.19 Bellsoft/Liberica

moving a dir with subdirs that contain some rar files (10-20) the thread never finishes and get this error:
`
xception in thread "com.mucommander.job.impl.MoveJob" java.lang.OutOfMemoryError: Java heap space
	at com.github.junrar.io.RandomAccessInputStream.readUntil(RandomAccessInputStream.java:112)
	at com.github.junrar.io.RandomAccessInputStream.read(RandomAccessInputStream.java:72)
	at com.github.junrar.io.RandomAccessInputStream.readFully(RandomAccessInputStream.java:93)
	at com.github.junrar.io.SeekableReadOnlyInputStream.readFully(SeekableReadOnlyInputStream.java:51)
	at com.github.junrar.io.RawDataIo.readFully(RawDataIo.java:75)
	at com.github.junrar.Archive.readHeaders(Archive.java:333)
	at com.github.junrar.Archive.setChannel(Archive.java:199)
	at com.github.junrar.Archive.setVolume(Archive.java:811)
	at com.github.junrar.Archive.<init>(Archive.java:149)
	at com.github.junrar.Archive.<init>(Archive.java:186)
	at com.mucommander.commons.file.archive.rar.RarFile.<init>(RarFile.java:41)
	at com.mucommander.commons.file.archive.rar.RarArchiveFile.check(RarArchiveFile.java:67)
	at com.mucommander.commons.file.archive.rar.RarFormatProvider.getFile(RarFormatProvider.java:57)
	at com.mucommander.commons.file.FileFactory.wrapArchive(FileFactory.java:683)
	at com.mucommander.commons.file.FileFactory.getFile(FileFactory.java:491)
	at com.mucommander.commons.file.FileFactory.getFile(FileFactory.java:416)
	at com.mucommander.commons.file.protocol.local.LocalFile.ls(LocalFile.java:829)
	at com.mucommander.commons.file.protocol.local.LocalFile.ls(LocalFile.java:668)
	at com.mucommander.commons.file.CachedFile.ls(CachedFile.java:479)
	at com.mucommander.job.impl.MoveJob.processFile(MoveJob.java:183)
	at com.mucommander.job.impl.MoveJob.processFile(MoveJob.java:190)
	at com.mucommander.job.impl.MoveJob.processFile(MoveJob.java:190)
	at com.mucommander.job.impl.MoveJob.processFile(MoveJob.java:190)
	at com.mucommander.job.impl.FileJob.run(FileJob.java:718)
	at java.base/java.lang.Thread.runWith(Thread.java:1636)
	at java.base/java.lang.Thread.run(Thread.java:1623)
`

**Comment by JamesOlvertone** [comment]
Tested with 1.1.0:  Has not this issue.

**Comment by JamesOlvertone** [comment]
Maybe 990c81dff45758745d52ca26d5035df7b057f6fb fix for #420 is the problem:
```
// trying RAR 5+ first as it has been the default for quite a while
SevenZipJBindingROArchiveFile archive = new 
SevenZipJBindingROArchiveFile(file, ArchiveFormat.RAR5, RAR5_SIGNATURE);
try {
    return archive.check();
} catch(Exception e) {
// fall back to older versions (1.5 - 4.0)
  LOGGER.info("failed to open archive as RAR 5+, trying older versions");
  return new RarArchiveFile(file);
}
```
My rarfiles are all format v4 and one is v2.
What I dont understand that the 1.1.0 that has not this problem has instead the code from above only the
`return new RarArchiveFile(file);` no out of memory error ever happens here.
