### ISSUE TITLE
Files won't open in Viewer/Editor

### ISSUE THREAD

**Issue by ssstain** [mucommander/mucommander#983]
### Description

Some files can't be opened in the built-in Viewer or Editor.
Has been noticed with python files. Some files are ok, some - aren't.

As a result you get a window with a message: 

   Viewer error: Unable to view file.

   Edit error: Unable to edit file.

Here're log console messages:

===
```
[2023-06-22 12:37:12.175] FINE FolderChangeMonitor.java#windowGainedFocus,323 com.mucommander.core.FolderChangeMonitor@6b3d490b: setting forceRefresh as MainFrame gained focus

[2023-06-22 12:37:12.249] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false

[2023-06-22 12:37:12.250] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false

[2023-06-22 12:37:14.541] FINEST EncodingDetector.java#detectEncoding,132 bestMatch getName()=ISO-8859-1, getConfidence()=45

[2023-06-22 12:37:14.551] SEVERE FileFrame.java#getTargetComponent,79 Exception caught

[2023-06-22 12:37:14.686] FINEST FocusDialog.java#windowActivated,228 requesting focus on initial focus component

[2023-06-22 12:37:14.687] FINEST FocusDialog.java#windowActivated,236 requestFocusInWindow failed, calling requestFocus

[2023-06-22 12:37:14.693] FINE FocusRequester.java#run,102 focus requested on javax.swing.JButton

[2023-06-22 12:37:16.958] FINE FolderChangeMonitor.java#windowGainedFocus,323 com.mucommander.core.FolderChangeMonitor@6b3d490b: setting forceRefresh as MainFrame gained focus

[2023-06-22 12:37:16.975] FINEST WindowManager.java#windowClosed,321 called

[2023-06-22 12:37:16.975] FINE FocusRequester.java#run,102 focus requested on com.mucommander.ui.viewer.FileViewerPresenter

[2023-06-22 12:37:17.098] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false

[2023-06-22 12:37:17.099] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false
```
Proper stacktrace:
```
>> 2023-06-24 13:48:55.552 [Thread-6] ERROR com.mucommander.ui.viewer.FileFrame:79 - Exception caught
java.lang.NullPointerException: null
        at org.fife.ui.rsyntaxtextarea.folding.PythonFoldParser.getFolds(PythonFoldParser.java:87)
        at org.fife.ui.rsyntaxtextarea.folding.DefaultFoldManager.reparse(DefaultFoldManager.java:445)
        at org.fife.ui.rsyntaxtextarea.folding.DefaultFoldManager$Listener.propertyChange(DefaultFoldManager.java:546)
        at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:334)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
        at java.desktop/java.awt.Component.firePropertyChange(Component.java:8732)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.setSyntaxEditingStyle(RSyntaxTextArea.java:3044)
        at com.mucommander.viewer.text.TextEditorImpl.setSyntaxStyle(TextEditorImpl.java:453)
        at com.mucommander.viewer.text.TextViewer.loadDocument(TextViewer.java:234)
        at com.mucommander.viewer.text.TextViewer.startEditing(TextViewer.java:211)
        at com.mucommander.viewer.text.TextEditor.open(TextEditor.java:261)
        at com.mucommander.ui.viewer.FileEditorPresenter.switchFileEditor(FileEditorPresenter.java:219)
        at com.mucommander.ui.viewer.FileEditorPresenter.show(FileEditorPresenter.java:185)
        at com.mucommander.ui.viewer.FilePresenter.open(FilePresenter.java:161)
        at com.mucommander.ui.viewer.FileFrame$1.getTargetComponent(FileFrame.java:77)
        at com.mucommander.ui.layout.AsyncPanel$2.run(AsyncPanel.java:109)
```

===

### Steps to reproduce

Not all files cause the glitch. The problem occurs with py files for me

### Expected behavior

Open a file with syntax highlighted for editing/viewing

### Actual behavior

As a result you get a window with a message: 

   Viewer error: Unable to view file.

   Edit error: Unable to edit file.

### muCommander version

muCommander
Version: 1.2.0
Build date: 2023/04/12
Build number: 79d6713

### Java version

Java
Runtime version: 20
VM name: OpenJDK 64-Bit Server VM
VM version: 20+36
VM vendor: Eclipse Adoptium

### Operating System type and version

OS
Name: Mac OS X
Version: 12.6.6
Architecture: x86_64

### Relevant log output

```shell
[2023-06-22 12:37:12.175] FINE FolderChangeMonitor.java#windowGainedFocus,323 com.mucommander.core.FolderChangeMonitor@6b3d490b: setting forceRefresh as MainFrame gained focus

[2023-06-22 12:37:12.249] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false

[2023-06-22 12:37:12.250] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false

[2023-06-22 12:37:14.541] FINEST EncodingDetector.java#detectEncoding,132 bestMatch getName()=ISO-8859-1, getConfidence()=45

[2023-06-22 12:37:14.551] SEVERE FileFrame.java#getTargetComponent,79 Exception caught

[2023-06-22 12:37:14.686] FINEST FocusDialog.java#windowActivated,228 requesting focus on initial focus component

[2023-06-22 12:37:14.687] FINEST FocusDialog.java#windowActivated,236 requestFocusInWindow failed, calling requestFocus

[2023-06-22 12:37:14.693] FINE FocusRequester.java#run,102 focus requested on javax.swing.JButton

[2023-06-22 12:37:16.958] FINE FolderChangeMonitor.java#windowGainedFocus,323 com.mucommander.core.FolderChangeMonitor@6b3d490b: setting forceRefresh as MainFrame gained focus

[2023-06-22 12:37:16.975] FINEST WindowManager.java#windowClosed,321 called

[2023-06-22 12:37:16.975] FINE FocusRequester.java#run,102 focus requested on com.mucommander.ui.viewer.FileViewerPresenter

[2023-06-22 12:37:17.098] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false

[2023-06-22 12:37:17.099] FINE ModificationDateBasedMonitoredFile.java#isChanged,42 isChanged = false
```

**Comment by ssstain** [comment]
by the way!!!! Thanks for one of the coolest file managers out there. I was looking for something like this for Mac and Linux.

**Comment by pskowronek** [comment]
I cannot produce this.
Is it always reproducible or randomly on a certain file? 
Can you provide such a file?

**Comment by ssstain** [comment]
if it happens once with a certain file, it happens always.
Yes. I can share a file. I have prepared the one. It's a Python file with destroyed source (I removed almost everything) and it still won't open.

**Comment by pskowronek** [comment]
cool, thanks, I reproduce the problem on the given file.

**Comment by pskowronek** [comment]
Short term workaround: disable `View->Code folding` in Editor/Viewer. Can you check @ssstain ?

**Comment by pskowronek** [comment]
Root cause in RSyntaxTextArea, created a bug for it over there: https://github.com/bobbylight/RSyntaxTextArea/issues/514

Workaround for current muC version: disable code folding.

For muC I will add try/catch to ignore this exception until RSyntaxTextArea fix.

**Comment by ssstain** [comment]
> Short term workaround: disable `View->Code folding` in Editor/Viewer. Can you check @ssstain ?

Checked. Confirm. The workaround works. Thanks

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)

**Comment by ahadas** [comment]
thanks @pskowronek, I merged it so it will be easier to check with the nightly build

**Comment by ssstain** [comment]
> Can you check?
Sorry for the late answer. Thank you for your efforts. Tried 1.4.0 nightly. Everything opens just fine. 
But there is a small problem with structure parsing when folding. If you take the file that I attached previously as a proof, you can see the problem. Just fold the first class (Fetcher) and it folds all the siblings below. I'm not sure that this is an intended behaviour.

**Comment by pskowronek** [comment]
> Sorry for the late answer. Thank you for your efforts. Tried 1.4.0 nightly. Everything opens just fine.

Great!

> But there is a small problem with structure parsing when folding. If you take the file that I attached previously as a proof, you can see the problem. Just fold the first class (Fetcher) and it folds all the siblings below. I'm not sure that this is an intended behaviour.

@ssstain but isn't that the whole file is kinda wrongly formatted and one may expect this behavior?
If you insist that the code folding is not correct you may create a bug directly here: https://github.com/bobbylight/RSyntaxTextArea - when they apply the fix, we will bump version to use it.
